/**
 * Textra Onboarding - Apps Script backend
 *
 * This is your existing script (Sheet ID 1zgAwpkowKm4s1cpELT1hh5LlUVSLz_gL35iVXWp-72Y,
 * Slack webhook, header list, Slack notification, script-URL hyperlink logic)
 * with two live bugs fixed and new portal/script functionality merged in.
 *
 * BUGS FIXED FROM THE PREVIOUS VERSION
 * 1. `updateDataSheetWithScriptUrl` and `findColumnByHeader` were accidentally
 *    declared *inside* `sendSlack()`'s function body (a missing `}` before the
 *    "NEW LINE" comment). Since doPost() calls updateDataSheetWithScriptUrl()
 *    from the outer scope, this threw `ReferenceError: ... is not defined` on
 *    EVERY submission - right after the row was saved, but before sendSlack()
 *    ever ran. Data was saving fine; Slack notifications were never actually
 *    sent. Fixed by giving each function its own top-level scope.
 * 2. The backend read `data.sceneDesc`, but the frontend sent `sceneNotes` -
 *    so the "Scene Notes" column has always been blank. Fixed on the frontend
 *    (index.html now sends `sceneDesc`) to match this backend, which is
 *    unchanged here.
 * 3. The backend read `data.companyName`, but the frontend sent `data.company`
 *    - so the "Company" column and Slack's "Company:" line have always been
 *    blank/"N/A". Fixed on the frontend to send `companyName`.
 *
 * WHAT'S NEW
 * - A "Portal Token" column: a random ID the frontend generates on submit so
 *   a client can return later via a link (?token=...) with no password.
 * - A per-client Drive folder, created on first submission, holding all
 *   uploaded files (logo, guidelines, character references, etc.) instead of
 *   giant base64 blobs stuffed into a sheet cell (which risks hitting Google
 *   Sheets' ~50,000-character cell limit).
 * - doGet(action=getSubmission&token=...): lets a returning client fetch
 *   their prior submission for the read-only portal checklist.
 * - doPost(action=submitScript): a second, separate submission once the
 *   client writes/uploads their script - updates the SAME row (found by
 *   token) rather than assuming "last row", since it now arrives on its own
 *   request, potentially much later and after other clients' submissions.
 * - doPost(action=emailPortalLink): emails the client their portal link
 *   (manual "Email it to me" button on the portal page).
 * - sendClientConfirmationEmail(): automatically emails the client on brief
 *   submission with a confirmation + their portal link (no button needed).
 * - sendTeamNotificationEmail(): optional internal notification email,
 *   separate from Slack - only sends once TEAM_NOTIFY_EMAIL is configured.
 *
 * DEPLOYMENT
 * 1. Paste this entire file over your existing script (same Sheet - nothing
 *    to reconfigure there).
 * 2. Set your Slack webhook as a Script Property instead of hardcoding it:
 *    Project Settings (gear icon, left sidebar) -> Script Properties ->
 *    Add script property -> key `SLACK_WEBHOOK`, value = your webhook URL.
 *    (This used to be a hardcoded constant - moved out of source because
 *    GitHub blocks commits containing a raw Slack webhook URL, and because
 *    committing real secrets to a repo is bad practice regardless.)
 * 3. Optional: once you have a dedicated internal address, add a second
 *    Script Property - key `TEAM_NOTIFY_EMAIL`, value = that address - to
 *    start receiving a notification email per submission alongside Slack.
 *    Leaving it unset is fine; everything else works without it.
 * 4. Deploy -> Manage deployments -> edit your existing deployment -> New
 *    version. This keeps the same /exec URL, so index.html's
 *    GOOGLE_SCRIPT_URL doesn't need to change.
 *
 * TROUBLESHOOTING "NO SLACK NOTIFICATION"
 * - Confirm the Script Property key is exactly `SLACK_WEBHOOK` (case
 *   sensitive) with no extra spaces, and that you redeployed a NEW VERSION
 *   after adding it - saving the property alone doesn't update a live
 *   deployment.
 * - Apps Script editor -> View -> Executions: find your test submission's
 *   doPost execution and open it. If Slack was skipped, you'll see the log
 *   line "Slack webhook not configured..." - that means the property isn't
 *   being read, most likely because it wasn't saved or the deployment is
 *   still running an older version.
 *
 * ONE-TIME AUTHORIZATION STEP (required before email/Slack will work)
 * A deployed Web App running as "Execute as: Me" can only use scopes
 * (MailApp, UrlFetchApp, etc.) that have ALREADY been granted via an
 * interactive run in the editor - deploying alone does not trigger that
 * consent prompt. If you see an error like "You do not have permission to
 * call MailApp.sendEmail. Required permissions: ...script.send_mail":
 * 1. In the function dropdown at the top of the editor, select
 *    `authorizeAllScopes` (defined below).
 * 2. Click Run (the play button).
 * 3. A permissions dialog will appear - click "Review Permissions", pick
 *    your Google account, and if you see "Google hasn't verified this
 *    app", click "Advanced" -> "Go to [project name] (unsafe)" -> "Allow".
 * 4. That's it - no redeploy needed. This grants every scope the whole
 *    project uses (Mail + UrlFetchApp for Slack) in one go.
 */

const SHEET_ID = '1zgAwpkowKm4s1cpELT1hh5LlUVSLz_gL35iVXWp-72Y';
// Set this once in the Apps Script editor: Project Settings (gear icon) ->
// Script Properties -> add key SLACK_WEBHOOK with your webhook URL as the
// value. Keeping it out of source means it's never committed to GitHub -
// GitHub's push protection will reject any commit containing a raw
// Slack webhook URL.
const SLACK_WEBHOOK = PropertiesService.getScriptProperties().getProperty('SLACK_WEBHOOK');

// Internal team-facing notification address - separate from the client's
// own confirmation email. Optional: leave unset until you have a dedicated
// address, everything else works fine without it. Set the same way as
// SLACK_WEBHOOK: Script Properties -> key TEAM_NOTIFY_EMAIL -> your address.
const TEAM_NOTIFY_EMAIL = PropertiesService.getScriptProperties().getProperty('TEAM_NOTIFY_EMAIL');

// Fields that carry base64 data URLs - saved as real Drive files instead of
// being stuffed into a sheet cell.
const FILE_FIELDS = ['logoDataUrl', 'guidelinesFileData', 'c1refFileData', 'c2refFileData',
                      'sceneRefFileData', 'musicRefFileData'];

// Textra logo, extracted from index.html's header (PNG, base64) - used
// as an inline (cid:) image in branded emails so it renders reliably
// across email clients (data: URIs in <img src> are unreliably
// supported in email, especially Gmail webmail).
const TEXTRA_LOGO_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAcsAAABACAYAAAB1AlzoAAABCGlDQ1BJQ0MgUHJvZmlsZQAAeJxjYGA8wQAELAYMDLl5JUVB7k4KEZFRCuwPGBiBEAwSk4sLGHADoKpv1yBqL+viUYcLcKakFicD6Q9ArFIEtBxopAiQLZIOYWuA2EkQtg2IXV5SUAJkB4DYRSFBzkB2CpCtkY7ETkJiJxcUgdT3ANk2uTmlyQh3M/Ck5oUGA2kOIJZhKGYIYnBncAL5H6IkfxEDg8VXBgbmCQixpJkMDNtbGRgkbiHEVBYwMPC3MDBsO48QQ4RJQWJRIliIBYiZ0tIYGD4tZ2DgjWRgEL7AwMAVDQsIHG5TALvNnSEfCNMZchhSgSKeDHkMyQx6QJYRgwGDIYMZAKbWPz9HbOBQAABmb0lEQVR42u19d3xUVfr+855z7p3JJCEU6dUCIk3siCsJCra168S2lrVgWV1d17a7ymR01V3bWlZXcbHXjL27IiQqKEovoUY6gQAhCUmm3HvO+/vjzoQAIUwgIH5/HD/HCSlz75x7zluf93mBfWPf2Df2jX1j39g3mhzU1A+DwUIZieTzrl0iBCCc+ofZ+qfMTBFAzC0ChZ/JZ0QivNXfpDWChUyRfNL7Hum+sW/s+giFQgIoAADk5UE09bvPrItwv7lBLigAExG3yPWZRV5R49dNXa/+GwVAAVru2rtzMDMVFBTIoqKiJn+vuBjIzQXy8vJMOBw2+3bkr2BIACL5urNTNaKVCwtZ5oYmqK2vp5rxvg3va9/YN/aNlhPov8Tf7up7eAp+39g3ds9Q29msQhCZx9777vpa4bu0ti6hDUnJzVRLDIYAIe66TvvW1OaQ9jmvnnNM30cKIhErP58SyWu1+2JJ1YlTS9b3rN5YfoQdsHvEEzAEbnLjK9YQRkMLyVIIam3TO38+58inALi/Bgtz39g39tJBRMSvTljR7bspU1t1aNc688ijDhi+jWtjABZgS4B+nLLg2x59+ldePaTzKiKqZmba2TMYCrEgIjOrmvuuKF9zZiwaNSwg4CoIWGwpQ3MXl31TVl5TFRB1JI3hngP648yBvTZ2zKI1YCbshec/tSbMbIdC/7r2zbff8iuhoLWhzUu6eZVjsZg57NDDxM03X/fFiBHHzgqFQmKfh7mXKctCZklEekEtH33vC+Oe+WrBWvj9NtgYgCQA3iqKy428pk6dQCzhoGuOwMm9/d/YXToUJg9RYlaMT3vr8zkj8h/95OJ1rq/jhihQWxeHoxu6oQ3fb8uvBTMIgEsKrhPFwG6tjl372qSyhy897s1QaIIKh4e7+x7vvrFvNC/0GSbilyLjBv1vUUVxqe7Z2tpAmDbJM3s5+Z93ApOHlBhV1e2RWVWO+cvXz51SziMLCgrWMjOaqzALCwtlfhDm+1HVv3n+y5JPSjYGcvzGgKDgCAaoDkoC0VoJcDYIrcAk8dP0TZheOquy8Kelt+UDLxQWFsr8/Py9KiWTl1cgAbj3Fjx19ScfjXtybXkdbNsGM4O5MUdD4Icf58D/7IsXMPMQogJNRGDe5wfsVZ4lANRGY602wWJXkmOEkAQCbZNy5G1emSWIYlBwUOVmugO6ZfvO7Nv6vjvPPmL0PwzAzD0f+mLGP/7y9FcXLqkCKqvj0BzXQoClFCSE3Kx3twje8hZfu9KAmMBwQX6pF1XUym5ZznAC3gzvIB+wb+wb+8a2o6igSABwKzKyLl9S7mtdoWzHZkeVVTmahYEwAJIR0pSyJBBIZskNta7WFf7+vZaU3RcOh68uQp4C0CyDNRgMGgbwXNnGJyevdnPWxymeabTULOFKDSABAkMpWxKBGD5A1ELEA+56+FvvV7bxJBCNfXrCBNoLVxcAMP6bokGLl650DaQTT7jW9mAjRMS1tTW0eMnyXgB8QLjGC0/vi5rtdcoyw6dc2wL5LS0zpCu1FCDs+Dm5wsA2FuKucQf0yPCd27/nA386+aDRBsAX89edfcvr3zz/benG/VZXgTMs6ECGlUw7ehqSG1XGjdw4AZIZzAZaMCyh5AHdOg4iAFxcsm9D7YYwUl5enkzPit4HSvg1jrw8oDgM7N+zW2nOuiivr4uTECAfQQEOhCBPZDCDksYsGcAlB8qnqCrumlk/r+8LAMUlz/BOxH/ZEsAN7822HRbstx3L1o5wyUsAedLBAGAQMRgJCIqCyYIQkpUtF+/taxyNJ2LKtpXjJEBEavtrAZZSEgPOZkFI+zbp3qgsAZBlSViKYFkAEYMahgAajcASFCXgukJ32a+NOrar76GbTz7obwAwZvy0s14dPz3yw6pa5Qjl5mQrRZxQ2wBzqd6t3BxyaCTKywKQSUuXCPApgYpNtT+zZ6ICkci+p9vC+ZZ0PYXi4mJsE5PfN/b6UZCXp8MAzh7Q9f33ps/6xzKlsrWwWMAlggGTAKABMAwng4UkQMJAwBUJrakyGh24gbl7O6IVoRCLcJhMc/ZYpeYu1742s4vLkpRgaEkAuRAMEBuAGARPWbukASGhhUuds+J0SPe24wHgD3l5XLyXrjExRPqhVAJaADC1b+x+ZQklAKUApUwy7GJ2+HClYZORyfKwztaMB/N/87d/XAC89tOisz76qeSduaviUvkDJhNRZbkGCenbRpoycRrXAZgIkgDAgMmwP8OPyXOWfMsAcvu1p+J9z7ZFAR8lJSvbPfbY48NWrVnFlrC2qdGRAIwxnJWTScNPPH7xtVf+bvauAD32jV/kQTOChRLAmo6Z7rScGuRuYmUkJ2RKTRLcLW1kQSChIZnIYb9rAq1bFc9b/RsAb+blQYTDSEtZRjxwu56wuHxQrfK3MagzfkFCs4GA63myyQsTeUkhJVwQiMlmGcDGsvP7HTwNAILAXhvVEKKF6vr2jb1LWUoloBRgKQaIdvjwCMwJTRjULrPm8hGHXk1E7rxK5+Snvpz0zuz1ceEP+NmmuAAIWvihGnE8jEgfayuMSJ4eQElGZray9j1StGitXTgc5lWlq3rcdNs9k77/aXZXKeV2QQZCCCTiCZStKDOvvvT274jorb0RbLFvNPHM+7UnIuIx3y8oXrCpZlhVXYIluSBIMABJDRF4DDICnPy5shSqExpLV27sBwBFyTxdWsoy4r3r+ur4BdUus99n2EIcAlYyopXacyKpLAEmA8DSlt+nMrLNJCLamBuaoIhoH7hv32h5Q2f7P3KhlIZlGUjL8zAtCVgqOSWgpKdMbcnwCQkS0J3bBsSRvTq8P6RL66nMbEe+m/rIjJUbld9vs7K0UIogLAlhA8ribaYluf7962dj11YEZWkI20BaEj7FsOHuy5O16MgTAHji1GlnLli8tOv6DdXx6k11unpTnbvNrKlzq6prdV3Mic+YVSrmLVpyrRCC8/Pz9y3jr2j077+OAWBgt/bv5igDGwkpJDEkwScTkIIhyEAKAykYUhlIqSCURIasI60dlDk4CgDC69alHVWI5JMhAKurE4fHHYdsBRKSYUkXUgJCGgipIaQLIR0I6UARYIRBjtQYkGkVpfKue7XAFQKUps/I+7IYvxZlCUjJUMpAKvLCsVYqLJv82qLkzwjSliC4om/7DJx53IDXAODtn+acO3/thgEx47p+i6W0GNIiWIrhUxrev7ec9dewGsxGrm0pgrQAYQFCaGT5iQf362X/Gg7Mr23E4y4xiG1bSCmFlFKobaYQSgiSUpISls0GMLQvjvSrG/nBoAGYhnRrs6RtwFoZUEwkwVIyLKEhBaAEQwpACkAIAyEMIBlKOaQdBxW1Nf2YOQvBoGkOwYBmtlduqBZSGEjyQpZC6M2KWRgoaSCFhhAaQhhmEZcBsymW2zrjIwBAUd7ebTCTaE5YHGz2BWX2emWpACglktPz9tRWU1je94UFGEvr/Vr5RedsX/Ehrez/MbNdsrz8L2WxONuZUkjFyb/zXmUj79ecWe9pWoBNCdExQ9PxR/ZdCAD98/L2mWS7A5vAaSOC9qnJX2/ikhGMCCLa1DVHTWsTkCyJ2ZIaQhKU0FDSeK/CQArP05PCAcgIl9jEDXWZsHz5wUlyAEoD3CMA8LSy+IEuuwOME4MljVDSQEmGkgaWZChJ3hQenoKkYb/N1DXbLDniiAPWIBRKG1D0S3qWzcG96X11lb8Oz1IJwLYA22JYScWYUlDeK3vhT4vAyuGubfzo3XG/iDaMcQtXDVuT0IOiMOyTRmzxt1aDkGpzZ/3fUnIa3Tag0NlnJp/ctf2nCIVEPu3jiP3Fx74Y0q92hG5oTwDQ2Y8P29iGBFwoJEBJRSlTU2goybCEpzwtLwplYsqSc1dVHg8ABUVFO3SlCpIcsNPLVx0blTaUYi2FhhIaUmjIeqXJkKQhhBcGFmDTJkOitT/xLhElQl7aYK8eUhDQjJDLvujMr0FZKrCQgpWkZF6CIZMeoZRJz1ACPgJ8BLYkZBa5tcd06vYZM9OMpYvyNiDBtkUmg7Hl38rUvxu8Z7ozdW3FkBaxm4ibQ7p3EsMPH3wvEXFhQcG+7bUXDGUp375V+JWOoiIDAEf16filpRObbFtKn9QskmFXLxzKXsRJCtgk4ROATQa2MogTsKE6caz3VkU7vFzJMxEGgPKamtwYCLYULKSBSIZeZTLUm3oVpCHIhSKmTEFm/47tvgOA/gX7Ikr7xi+AhrWhLJ8ypP2albRZGIAFgzgZREiSAlgAHCV0QCnpt3hhz07+5UTEd7z36XEOa/JbJKTRIEFIVkjBUPLvjfIQdUjWcLKBEQywYiYGSHvJcPZq4Q2xB35lcILZSCeujj2ws3VYtw5Pn3Bgt8+ZWVDTXiUxMyKRiJg7dy41PMh5XqLTFBQU7JHuBV6Rf4Hs0KGEI5GI2T01iUy5uXkSyENRUYFuxueiYDAoKipmydzcXGiw2AFVb8PPxUoqLFzw85S7775HTZ48WUaj0SYNmA4d/sCRyC4jZikUChEAUbSTDE4dOvyBCwuDZmeef7KbxC5dv+FeLCho1vNq0eERSoTEIe3brx792ZTp5TVymHak8bMruT7nlqK9M0n3x4ABCHKFcQWqYqYvM1tUUKB3XF8Jw8yBv389dUjM1ZCKhTKAgIZLjIQQkCSgiAAGmAED5oRDMlvXVZ9zxMHTLgcQBDg3N6SKi4vSZAzqwJFIRO/qGQsGI6K8/OkdGekqNzcXRFKgGaFVrXk3plWaloXhcAHvjYxBzEz5+RHRr9+W9w3kIS8PKEjuuZY+P7QdfkjDzN1Hf/TF/EmbKgM2W1AuoMWW5ABGeKwaCQPkZGWht3HG/jN4xjUrgK7/+uDzWQuqo20giDmJ9UjquuQx877LSVg4EUEKAbgMNgoQBgYJEAsAKqlgPYUqSKBDVja62rJ2yIFd/nLGIYc8xdsvgqdQKEThoiKB4uJ0IeUiNzdX7C4mmu3UH7Z0Ef8277ezdY/vfzTu6rvv/sfzS5aucn0+n2qqqJqZXb9tqQ4dWl07e+aEMbtyv+mXtxQJoPgXKRfY3dfPzc1VvwQjUmjCBBUePtx9YdKcv39TwX8t31Sj/Ugot6lmCkQgMFxNfFCWTNx08iEDD/LnLEoasaYJPlpTxtzr6U++XzK1Og7L9jGzJhIMv7AgEwKxWBTxRAw64cLVBiylzgjkyMPamO/uO/v4vPxIBJE9VKKUMnSLi8PNfuYnn3rJw1Onzrst7rhu0ww+xI7jUI8eHcrnzR5/ABHV7qqMYGaKRCIi/+mnqRmyUOXm5v7SrFwUYqaivDxRXFxskHYdba4KBjtwYWGhaQnFuc3DChOZwsJCSUQr3vxpxj2qyveXddVVEkIJw1sqV/JICGAIbptAQPXO8MdBxBs21rS3lGjD7EJJmzw+Sc/6JHiuKTEDkuFTPkATTJwRrY4iO2A57dr4o8YkQGSBYWAbkfRomTP9fm7dKmdtj9atPh/ep+8zHfy0CKGQgGcFbWV95ItIJKLD4TADMNnZWVi+fFPrrz7/dMj02TP9CxcuYteNU6s2bXjoMUOBDHvKdZcHN1mWqi4uLjZJJhoZDAax6xboZuFKnjGSecstfx25cWO1efnlf39KRLqlOgukahuZ2brskj+e1r5Te3r00Xu+IKLYDq5BSefQvvXWe0YsX17mVz7SEyd9f0wsFoPw+M52hOATiUQChw4+dNShA/uW10RrhM1Wo9djWxqfUmLkqSPXXn7Jud83R5knP0fSC4JhZjF+/MT958xZOOCbb75ppM3T1kJebyGYtNbo2bUrP/7vBycQ0aYdCabUGje4vv/lSKTdyoVlR06fPn2r66fDEujdj8/nw3HHHcdDhhz14/HHH1FWXFzspvYhM5s95W2mQHI9u3b6Jqfi57+tM3HJSu3gk3gCwkjSWkjf99MWDQCwKJm3bHQP9E8e2rkr1g6ulYKllIbIlX7bB8RcbChZiqoFqxCvqkM8FgO7GkSAJnBG60z0HNJjHNEwHQwGJTO3Ct//xD1fjxvfUWvDRI1n/BhsMgMBMeCQg358/PEH/z169Oi0z11ubihVx+kGAhlYvnxFq6effumo+fNLs0tLf2ZIJmhANyS70oAhFkKQqdhYfYg2Btu7t93nieWnom4aALKyMrFpU03OO+98fszMmbMDixbNY8dxKTOzFQ8dOhStW2dOu/DCs9cRUay4uDjFyoVgMChbSham5/0XykgkX4e9fW98PhuxWLzV++9/2XflyrIuEydOZMdxCAC6dOmAIUOO5e7de/w4bNgRFUQUj0Q8VDEAGQqFeFfkK6XRUianyjvtjR7SHABVydf5gHsI0aZxCxf2+3Tu/Dk/Rx2SSkCwhjAeGbLLBkLY8IsMoNLFumVl2LisHNF1m1yKaTX4oJzI68/99drpi8rUAb07u41dB0Atkdfiq5BZbg3oafhAmZkefOSZIydPmnx6XW3i9LVry3sZTW3jcQexWDTJCCKQnZWFaCxa26lTx1jr1tnfH3Hk4RNPP23kx0OHDpyrtakPTe7KRknRfzFz1sWX3PDZD5OnHq8N4cDevd4f/+VbQSLiUCiEXXmgKWXIzNawvHM+WLZk7WnKEhg27PCvX3zhyTOIKLodhUlJj9F/2WV/+Oq7idOO05ogJCMWSyAWM4BIU04bCduWyMhQYDYglo1y/bIw0MZBl877YchRR5zw1FMPFqWzxqnnq5TEm2++M/TV1z84c31Z1Wkbqzb1ZmJ/bW3NVvTCopGtblCfU0iqRWVJHNJv/28//fj14UmlZLbn7RUXF7sZGRn4+98fO/THn6aPWrV6zSllqzZ0kFJmRWOxzSEYFulxsRAn6eMIgYAfJGhT27at5hzUp9fHN99440eHHdZ77h4VVgwCgZk5Y/Qn4xcsjNndHSYWMLQ9MUIePwhcUm5rW6iDZez+O3+be3fKS23Kg31+ypy/TKuIPbB+Y9TN9PnVhvnLUTphCurKKyEsC5YKwCdsKALAGgnXdXNakxp0SObV//nXPWMB4MY/3fm78eNnvLps6WpYtmrC1CFoN4GePfbDuWef+rt7773z9ZRQ3hFBR9KYbP3woy+NKppQfM7Spct619XF22mXkXAS4BTVEG+GhRAzkHSsE04ytCrMDtmUHMelHj32K5/w1ZsHdO7ceac8y61kYeZLr350/LvvfHR0NFZ3xvry9fu7LrdLJBzEY1GPdEIKBAKZSMRjda1aZazz+62fOnft/PmNf775f6efeOzK2tq6FpGF6cqxlAyfNnv+EU88NvaIlSuWn1tTV3fkpqqatgSJ2traepIUZSkEAplgE9/UqWOHtT6/9UWvbl0/ePq5h6YTUUXq7BYVFe1UioPSveHmjG+WLu330Zy5c0tr45CSQGw8i5MMAtIPU2mwbOZylM9djpqNNVBawmblZtg+dXDvwKuR10OXpRMmQlGeaQgV32pDtw/d968bvv3mp7N+XrL0sJqaKKJ1CYAJKQtdNOCe0tpASiW1dqEsQnZ2Ftq0zYr3Pqj757kn/mbMXX+6/vN4PAEgKJmb79Y3UGJZF1x03efjxk38TTTKCQggkGHZRx894P3PPn51lxRm6mDEYlW9zzj7+qd+/HHOya5jHG00B7Js+6zTR3z9wn8faVRhpjyljz4anzs6dH/R3HnLEpmB1lKbOEiAhLBF+k0kCMyGjdGG6lt08zbn3IDBbBwltH/I0YPf+PKLty4BctUOQpoSgP7yy/FHjH3xvXtmz5511trySsTjBmwIzKyllI0oxq35hWmL7U9EnEjEuH37gHXn7TcecdNNV07beo2SBiQAcFHR96e98PKbf5v0/U9D1m+oFbFYApIsGK23vT5tp7PdFl+LVHICxhgQQZJgBDL96Nplv/hxQ4985e7wTQ90btN5qZeXC+/2sHOwsFBG8vP1f7794ZmZ1eK69VGtJeJq67XbonUeAQ6EsaUQgzJ44Z0nDR0Ijwy88RxSMCgRieiHxv/w6Zwon2a7Uq/5fr6c9tUP8LsSGRkZgF/ASAKMBlwHRic4Fo9jwP4d+C+3XHjMb34zaAoRcNWoP48tjHx1GRupQUY2VfxvjHEz/NI+77xTnn3uP//4w7Bhw1TxdkKTqTByVlYmRhc8dsdHH319w7Lla3pu2LDei68RGSIwSGDb3IpI0l2nCOBJAIJ2lArcVWW5lSxs88A/nrt+yrRpo+aVLO5ZXl6JWCyWOqcGRCxINlwbCCEkoGFZEpYtsF/7tnWHDho0/djDB/zzrr/e+HE0Fq8/i7sj9VBcXOwys3jttY/O/3rCN3fMnDX3iFWrKlBbVwftaghBMMxaCqu+B44x3tkRkiXYIMNvw59h4ZCDe284+sjBhTeM+t0T3Q7otmBnjU61o0R/c4qKI4BXtmHbkFJCSQNS3gbSEMjhDFSUrMb8b+cgurYOfgqglcwAWwTDBKMIQkrBzHTttWPUc8+NcpvYTO7WiiIcDmu/34e7737shpN/e+ndc+cu6lxZWQNmgpTStSx/yswXTAYNE+3SkgCDpWWDwaaqehNXVFb6Vq4sO3vu3NKzTzv9iuLgBefde3H+yeOTfeWaGzI0zJx14SU3fP71hMm/cRxybZ/PZhjE4glnypSSc049/fJCZg4SUbMNldThYOZ2F154feGMGQsHuy47yrYsCzZiUcf5/LNvT/z91Xd+zMzb9TDXr98omYmVT0mSRiopwDAAN0c2uyABkoJkvVBtZKUESRgj2bb9nEZLG8rNzZXffvuNe9dfH/rL3aMfvWfRorKMWDxqbJ9tpKWExxhMknkrK7CxQvCttzURhBZudqvW3LFz50EApnkMRputWyJCZmYm//G2e+++/a7775s/fzFcw1DK79pWQBAZgrW1puQ0Q2XJeyIBRdKL7EJytE6bkvlLfStXrblmwYJlZ/xnTOTW60cF3xw1apQ1ZswYZ/eGwIKIMFOXeYveL62tvH49tFBCeMHW5NnhBlzfnmdJUGAybLDJ5Q5lQE4XonWNyxGmUL8CLmAO/O3TCQcoKxtlU0tp7uc/IcsKQGYTXBODW1OHeM1GRGsqYRIJGKM5oRMi2r7/rOOOGzgdgMUMJzuzlbSUUAnHISKSO/LklRUQy5evWtJUDj7VjLpsY7TXHbf85bH/jn3znKXL1kAp5Vq2LQAmT5kml4Qae7ANraIUlk+k6+HvzHOT4XBY+2wbd9/72DWnnX756LlzS7uVr9sIgIxlS2PZtmA2REIJNlsSISTTBgwoNswmGtO0ZMmawPJl5cdN/WnaRyedcunEs845674rLz/jy3pMSAukj1IyrLi42H3lzfeHXnjRH56cOWv+EStXlsNxDSxbukopUkqm5LhsuK0EpEfLSMRE4IQ2JlYdl99NmtFuztwF1xd9M/HyUOjxlwsKbr6XiNaEQiEVDqdvdKq0yJXTbx7LAGAnvPVWwoFREpaW8AmF0m/mY3HxQvi1Hxm+HNTjY1mDjQYZB9AEIuLc3FDaqNTc3FwViUTcuXMX977nngf/NXbsm78tW1sBYQnXsqQAk2CG4oZGEG9jPaZcIo+8SCooZTGzMStXbqDyNZNzFy1cPO6GG//yr6efeiBERDXpKLQtPMqLr/ts/PjJv4lGXdeylOKkAlLKsmrrEs6UqXPOPfW030WaqzAbKEp1+llXfPzNNzMGG2McZUmL2UMpWpa0qmqjzsefTTjxd1f88aOkwoxvfQ1hS2ZSRJxEODLSP9gNnT9Go57Hloue5BxlkNmhVMiVxcXF7lnnXBZ+q/DD0StWbUCGz9I+v08ycz3CkOvhYzsSONxYshbMTAJeiH8rj5J8PttceMl1b7z91gcXLV+2VmdmBmBLSGZWgMYu148nt7u3F4kAQ0JAZPgCiNVp95vvpndau2bdG3/8w5305NP/fCOIoIxg94XCgoABEQ+pqZk9ddX6KkvqHC+o2CAUS5vtDkqGICUTaWO0a9k5E2ctGATg6xRR+pbyAhSmsBl5+TXdLTvj4IqFa3nuF5MpYNlgSqBuQzlqq9chHq2BdhMgciGJ4Gph/NmKOndv+x4R6YMOOkgtXrwYgazMDt7apRP6NmA2kHL7lDqhJMnBxrLo/qOuvXX8V19N6hWLO05GwK/ApgHQjTY/e97psvbtNB1prlcWUpFI2J0xf/7+4Xse+td/x7521pqyCkhhuT6/LQEWXN/5hMCmUTnY8MkKQQI+28fMzMtXb+CytT8ct7j05y+uuubPT732yr//GA6HeVfxFg1wFvLaP9wRfvDBJ/6yfNkaobXQPp9N0mJPhm+zII00dWQmr/c4hJQSyrK4Jubon2YsCKxYteH6ST/8kPv8i6/+4ZrfX1rUHO9Y7ZZTZgMsDYQEBBHaikzM+Xo6Sr5bjLaiHaQS0G4tEtEKxGK1iMfq4LoxEIC22T0BAOnCv1Mu+xNPvDjkiitufGdx6cquiYRx/Rl+aaCVMSZtLsbG8rYAS9tnAQa6tHQFVWysunXjhpqRa9fWnNSxY9aaptz5hooy/4JRn309YfLxiYRxLEtZDR86G4alLCsWTThTps4696ST8yPMfH46CrPBNdTxuee8P3v2omMZcNXW12CGbUmrrrbW+fKLb0Zc/vtbUx5mLBQK7dXF3Lm5ueqbb75xL7nkj+EJxZNHV2yscgIZfsWG5e7oHL91z4CCggKZkeF3r73u9jfeLvzkoorKukRWVqbNbLAnCFaYGUIKlWFJs2jRMjiJ2Ot/+9t9dP/997zeUqCw7RnKIWbRkWjNA19N/CbbZ58ejSeMAGT9CtG2kUEiBgtw3DCt3bixP4Cv5xYVUSP1nAKAWYuqk7VRmP3xdG07jkrE12H9ujWIR6tBMBBMECQAISCEYNaubNe2DR33m6Efv/78v2DbhzGweLcg1pm51aWX3Tr+888m9BLScn0ZPssYvVd2BPFkUdh95vnXj7j6sj+/U7pkVa9YLK79voAAQ3G9ZqSdlIUgn20DDP3zktWifO2Gm0acdPGRLz/zcP5+3fdbuaO8b1P3nVSU7UecdMGzCxasOHfdhg3G58swSgrp3TfvdB8WNoZICBUIZPKGjdXu95Nm9Fu9eu24G2+869Jnn334TdfVaYHndpuQFIohiNFGZaN0YilKx69AR9EO0omhcv1CrF45FWtXz0fl+qWI1a6BjleA3SqAE81a5OLiYvffz7xw5etvvvv97DlLuhqWWtk+ZYzxzKYWAJ0lvTNpZ2SJquq488nnxQMvuuTKcYWfFHaKRCI6WFgoG9tc9aHXi6//dPyEH4+Px+EKZVvbCPhkCY2UlhWPGWfGzEXnnnr6pe8wM5IeIzURbmFmbn/GmZd9NXfOkt8yKy2EbLS8w8DAsnxWtM44X3xeNOKKq27+mJn94XDYzG3fnnYp9rPbFGVIFRcXu08++cItM2bMG71xfa3j92VabFzaUwIoHA67t93xwHVffDnxosqNUSfDl2kbs2cU5ZaHnoU/I5OWLl3LE4q/f+399z8ZHA6HzW41doqKBJipW2bGOzmKiMBe4/XUBEPAM4oFeWdekoGSQEIQamLxE5iZ+jdCql6S/F4iRoOnfTON9Kpyim0ow+oV85CIrYMSCSjyWHyIPKOXCUxkKCfLV3b9ZeeXAqCSkvIWNxYKCgqImcUNN/3l+c8++7oXSdslqRSzSSNj0HK1X8YYrF27Np0QpopEIvo//33lktdeefOn2XOW9HIdpW0rQ7IBcb2yoV023MAkfXYWRWNwJk2cfuz5l18z4c033+weieTrYLBQNvP9RCQS0SUlpX3Ou+DKKT9NmXfuxo0Jx+/L9iKCMC3SsIyYwJpJSduSVsAsXlxGX0/4/o07/3bf41JKvcOw/W5TljZAQiDLF8CGxesxZ0IJWvmyEK0tw+qVU1C5fiE4XgUhHFjKeFyPJCDgNXpNH1Ic0a+++t6VL738ztjpMxcYX2amYSJpoJMJdQHaRZpSwSJ5SA0MGwhbWSzInTxldv/HH3pj3CefTOgUyc/XWwksSh62zAsvvv7Tr8dPHhaNsystpZh1oyEhkAazgbB8Vl3MdadMLTn3NE9hUipHurVHGYlEDDPLESMvfnnylJI8R7sO1ecJG/ncRgCGoWxl1UbjzhefTxpx+RV/+oiZfbtaSL+7IO/FxWFdXl7T+a3CD+8p/Xmp8QcsqZthUGHXOnCISCSip06aetCX/xv3UOmSldrvDyj8guTWmh2yMiwzc+YSvDj23f8ys8TuZvMh4hG9DvpcOvFKpYQQ0Ow1IkkqRsHeJG9KGAgyImYYUVcfCcDKz8/X23AGRyJgZpo97uduP0+aj02VJahY/zOkh25qICM92UDEcLU2Pr/N3Tt3+piIqoPBoACKW1R7FRYWynA4bJ5+9s1zJk2cnV8TjbtCSWWSja/TC/O2FCg5PVkYDofdN97+MP+VF9957acp89mXYWsSrmTopEzVW8bMd1qBG4AMDGsIJSyHtTtlyoKDnnr6ra/ff//97pHINrKwSUVJRCYa5f3/ds8/xn/5xaQeBuRK21jMGthc6YJ0SVF2mOYgDQMt/IEAlf5c5hS+/fnNd4cfekwIcnNzc9UeU5YFqS8SgJIGIkqYOWEe/K5GVfVirF49G65bAUsKSFhAMozFIBgW9Uw9O0bpBWUkkq8/H1d8+H9ffGPszBmLTCCzFYzRHnCn4Z7YZU5v2ozkJPZKIYgVkeXOmlna/78vvP4VM7cNh0sotUlyc3NlOBw2f7r979d//8PMYXW1sYRlWZ6ibMTTT+VuQQAbAyktVVcXd6ZMnXPuiJMvSClMCoW8HeOVoHih19zcMz+YMXPhqXV1CUcqaXET9br1S8IayrKtqupYovibySP/es991xVvleim+rn5v/RXjDwUoCfiGn0vatATEdtnspEA+PbbR9+9YOHKtpZtG80J4YEkaLufkbyWwN7c4rM0PTffjbeG377wLVlK4dmX3nho0eLl2X5/Bhs2xM0AQjfn2mnijAGCBGw9e07pEbfcUnBGOBw2wWBQ7iY2H2Zm6t41Z11Ohm+Rz7YIShohGCTYa/5MQIry1PuaQDAiwY42tq/jh9NmDQGAwkhEbFUgrwHkLJg867BVc+eirq5MSOl6RCQsAUgwSxgQSHCy5MOl1jkBOvqowZMAUL9+/Vpca+Xn5zMz2x9+8Nk98xcuNRmBDDLspkVms5mnLIVZ2xIFTruhxCISydevv/PVAf96/Pn/TJ++iAOBVmBo6Skb3g2RIgaTAcNACKGk9LmzZi/q/eKrH41j5g7hcJh2rDCZ8vLyBDNb5wYvHzOhaHJXogxHSFIMp76UqmWjXQyPGY5h2KWMzGy1fHm5+/Yb7//p9rseOKu4uNht6hztFs8ygQQCtsTKOStRvaQO8U2rsHHNfFjEkMLvbSNi78x7xVze4gudTikfRfIjYGb7gfv/9d8ff5rNgcwsZuMKIt4sJOtRB7u2yIY4WXLmeamCPdS3JKkMG2fSj1MHXHX9nx8hekeXlPSnFO1SEjZ+4KbaWhaKiNn17quR7tYMAU6VeyfL+yzLsuqiCWfa9PnnjDzlgmRIlowXFiTDzDm/GXbmB7NLVv427iQcpaTFvAPRm9woMMJDCFtAXSyK9etqAtsqVW6A3msB+5g3X37zFAALECejCluCCKm4uNhdubKq3ZSpM86trYsakpZgrx9OE1t367CNATGnMb2QPQPQ7O3Cp754Kj5xWukBU2bOPau2NsFSWJKJm2l/cSMCyzRARXIzjWMFwRLSZqypqOCZJSX3MLOKRCK7KzbIBUVFUhtDfqPfzVICDoi9HesZeGIrJQEiCCkgOM464FeOHTgVANq3D9JmheQpzr8/PnbQnJKJbRPRMuMjy8uAUgOjkrwaRQMNsGBilllZVH3OOSd/BYALdkCntzNeJQDz7IvvnLp85dpBJAyDWXrnvxGPkql+ent6s5lYby7SZuOxJV3LZKoHzJxZ+Ma7/5s9e3FbX4Zt2GhBRjao8VWby7d2mdNC1JdqUPL+iLRiCOf7SXP6XHn17U8IIRrIwu15w/miuLjY/eMt9z03der8EY7rukLBgiaQUQ2qxGSLyPF6M77eiCYYjpM/4JdLl67XX31Z/Oq7737WLRKJbNczFrspCgsR9WH5zGXQm9aict0qSGWB6untdimHJIhI33Rz+OmF85cfpoRlGCy3LATeEyFCA9vyWZUba9xJE6f//un/Fp7uxeyDMi+vwACgy0ddPGbECUMcN64tYluniG3TzQ0oaVtOQrszZ8w757zg1e8xc8dIJKKZ+cCrrr5z+uzZpac5rqullFZa65o61EQAu66SsPv2PWDq5Zee+e+URWWMJsNsWBCM8IgDWLgwzWg+b0jDkAsW2vt7EoDwuIUbTggJQRYEBGMrdqi8vJAEgNGjQ6dsqqnrJASZZCunJiWLIeNdXxjvOkRI6uQdTpAAsWRmslLozmef/vcZq1eVC8uytDG62Y6BgdfY01t6Tk6ZnB5PsqHmUQMnWVkls0HZ6jWHjx37ymAAu8277L9uHYOIe3bp8E2AXVjERII8D1J4gB4iQAiCEN73BAE+khSLO6ioruzDzPTMus0KPcWlOm3q9GPXrVkvlFLGcFNnmMHQTILRrWvXkkGDBq32HlHLMhrl5+cTAHz+4afnl5WVs7IsbvRscUMYcMr6E8YxRscSro453ow7rk4ktI47CR134toxLdd0Ky8vTxKRue22ggcn//DjgUJIByC5p9FHzARL+qxNm2qc7yf9eOHTT798fkoWNpFCMy+//ObpE4qLf19ZVekoZUtsU/OF3d5HxBiQzx/AokVLs98qfP99D9nuGevYE2jYHp07ofbbOahYshbRyuUg44CF3GVFmUT+6ZfffLnP44+8dUV1VUzbfltsLhagPdZ/CuQl3zN8WbR86Tr+/KPPHmXmLwlwvXUO0eA++0+fO/fnYRvW1bw/efKcztIiTcQy3dJVrz7UVtFo3PnhhxlnnXr6pfa4ceN+f8KI/Odnz1yyvzGWIy1Y6a4rgyFIgI3rCuGqAf17T/vPU4+fNGBAj02jRo2yAOj9O3dJ+H22iEUdVwjLGMMQAiSFTH9xWcEYzca4XG+JciPlGuSCtWsEhPL7hLslqXkJMzOdG7zqwsrqOpYynesTCDaMYaO1mwoJJBtxbs1KsNUrEWvHoWhdFW1Yt3ZqasVWr1p9ajTqQClJbLhZwTQhBLsaWruamA2l9o23Ft51SYClVCCCZDbN6oAmpdKVlXVyfNGk4wFMKS8vp90EcjIAcM4hB80oXbn6Z58UBxjDhkgLQcJTmA2eLZOnQCUTJbRGVcw93FaKHa116oMXFxcbZrZOO+eq86K1UVhKEcDQW1JWNihJAbR2TGaWX+x/QM/PEokE5RUUyOJwi5IzUJK6MHPgocOP0tqQ9ApLd8i8xMysdVzk5GQjEAigYVkJgWDggqRATU0UtTUx0A6bQCdLO8BoDN+TkoWffD2xZ+jOe0dVVtVqnz+wGfG6B/nPPaonA9uXIZevXMuffPK/R5j5EyKKN1aPHonMZSklv/7Wx/cuWbIaGRkBsRmTsQcVZn0EkqRm4U6bXnLkbXf+8/xHHwq/VVQUUsCWe2u3KMvO8GHDyg2oXL0Kxt0IJS2YFrCnwuESYmZ1+VW3PFG6eJny+WzNxLSZkWXPbQ9P6hkAQjLYnTN3YZ/HHn/+Ivxp1CsFyWLXUCgk+vc/YPLLL380ZN36Jz5durxsABvpkiCVniNhPIWpfNbGqjr9w+QZp95wU8HMteUVHbUrjLQsLxGe5mcnArRxXSm06tO757Rbb7nppAEDelQkD54TCoVE3ogh37d5NPPBAf33/0tNTS2ktBCPJVC9aZNXE5nWbTNysrMoIyCSFHrKC3NuTWNDGgDZ3bt0Wjdy5InPfPjhG+R1ggBFIhHt9/tw9NAz+rmayVKp92r60BqXIQWLdu2zIKXH/E/pUM4xw7It9B9w0KfXX39pyQ03XAZjeL+8E847PB5zkJHh83KVaYX3CUTgWCxGgQyfymydCcuSDcKvAoAAs0AsmkBNTS3irqt9Pl96pTBJRhgiSfGoSzWbErkA/lVcXMy7rYRkwgRFRNHnv/3xm0zXHFATdQwRCwneBnCuyRPztiGqE8ybjG7/6axZvU/q339RKBSigoICJInV91u/Zn0/dg1IeeGFzcEu3ibSorUrc3La6AGDBryfZLoyxS2b/6NwOGz+dv/9raN1sYOSz5p2aLawNoZZHHnkgGX9+x5wf69eBy6Lx2PwXGUJKCCRiMpARraeMnXmDRMmfH+28dBCckfkakSEjh23/WlJSQnZtm3ee/Pdx0qXlPlsO6DZcANogWkR9Gv68RPyUJ0k3DnzSns+8MBTlwN4Li+vQKEB9ZdX6hd2H3nk+WufePqlw5iV3pyDapi2EHtAiqdwKAzL9onVayv4x59++hszFyZ5dLeoi1K760bWLV2J2qp1yMgw0GbXG2qkilanTi09YcnPZadEY3GdnWVLt94aF7uhccf2zoeop69iaNi2ovLyCv524o+3ZmRkvBIOhzUACofDJjc3pC6//Mzl//73iyNfef2d8fPnLz+EDVwiqB15w0QM9uj5YFk+qY02q1ZVdRRSGqlYMDtNbCre5tBp47pCQvU75KBp94ZuOmnkyJEbUmwfKcamcDgMIeivL7/xzkdTfprl9/uV2yan4/ljX3jl5rI1Fdqy7B0JdC2FkXm5R322/4Ed/lFZWSmk8nsPyQG8nm7eq9EJ7tixJ1152aULOnfOLk9aoSlCeV5VsbHbyOHn53hCZ8en3rAxtkVi2LCjpgw4tM8DdXVVG1zXBWmbd+QBJhIJ6nFAD3P7n677MWUJf/fdd4HamlhbIgHmZH+oHWoxAQJzIh6n3gft7xxzzIDIfvvlfOC4zlrvXgy7AKQU5LhAXU2is5uI3zRl6pzjli0vg+3z7TgCQymFTDAGWLOmvDUzy93JzZ0iVm/bJvubzMqaKzZFPeY2agwOl+SIFV4WWEu/L7OssnIIgEXIyxN5eQUA4D782DOnrC9fH5BCuAArblxRp74yUknRqlXWtD/94eo5qfPVsujnEgKAVqrNMY7DBJBmhqTtnVNiEAnjOAkaMuTw9Z/97/XhGURLmrrGecFrT1ZCIK417/h5NX7dlFdZUlLa58qrbjozGnWMP8OSXI/S3tOlX0mlA4Zl27Ru3Uae/OPkW5j5v1sqHUIyouA7+9wrblq3rpKV8sMDPjYAUu7JCCEYEAIMFmxIr169dsDD/3ziQgBvbM3wo1q2Nsl7nbuoDOsX/QyYBAT7AW4aFNEwl6ksq9HfefrpuQQAr7zx5lnzF5SyLyPALm9tgeyhTUJb1yyR1JrMwgUr+r3z0dcDfzty6OwUWUFxcdgNhULqxht/v2bOnDlX3HXXwx99XTS1o7KhCUImg6ON1m7xVjlOghDS80nFjuWp9irgWCSFqnEFQR06sPf0R/55/0nHHNNvw/YIFYxhcemF5/2Q+vd7731xiG37k5ZyOusj0L17Z9wXuuvbdH79b3fegMbyTyoQqI3XRROCdpyPJiI4joNevbrU/vMf91zYp0/P0p15tHfcen09I9K4cRNNRUWV6/Fk8g48SgMmQLDF8Xg1n3DC0dFbbrrx3JNOOubLHV0zMzPw9gMP/Pu2Z5995cFlq8qFsnyEVNh2a+BTkgqZWEIIEjV11ei5f48jAbQDUL6zbdjSYPNhADjsoC6Tlk2eGV1L5DcEKG7owXCqb7yXP5YCFhs2AKKk8pj5tUgkwmF4BAXTp887oXJTjKRFSUpFsdX6bgZAaU0mI+ATB/XuUTRtcgK5uR6jU0t+xrlzPWTtmjXlHZikALQrWSQbDDYGljNwNXFOq1bi2KMGPpRBtOSUU27yZWcfv819bdr0rcq+8niX3pvg47RIY1IMO9vWWRYVQQDgF195+6plK8ulTykN1mLz2tEejbSZZEg5mV6QhmEWlq496O33Pj8cwE8pOVNY+LbMz8/XH3ww7tglS8v6accYS7I0WzzzPcmPIhrS/sBn21iztoKnzy79EzO/uXVv5Bb2LD1t+e3X32HN6lX1YbDmOMbZrVo1+pPiYo+ndshxZwyJRmMkpRLMe009IKSSpqpqk/Xlp1/9FsDs8gaQ9nA47AaDQTlgwIAfX3rp4yNWrl71ZWnp6v4g6UKSIjbN2dyUns2kkqk4gmHtAlr1O+Sg6Y/8866RTSnK1P4PBgtlp05las2a79zq6ppAc/LNSZxGJjPL/v37y/79++umxPDWDZeTBNBoTbSxe88ja5RSxNjhIrEQQsDwJssyq4LBoCwvL6cOHTo0a5dEIoWmQRGUlzhO89EIEhyP1fHBfXrh6qsvu+Ckk475sl+/fnbTnx+IRCJ0881XPnL36EfbvPRy4V83VtZqpZTkvajtLiVb9x3gz1nwyNdff5GdmXlOTbTOy8F7YedGQtQGQpCIOwkkoI5q0MmFmFkOOfb0g+OJBCylRFP7i4ig2RXZ2Vk4fPCgrwtfA5r7XJFWSWkRAGDhwkWO4zhp5BUBANIYg/fe+/RDz8iCA+SbRlio6Iv8p3Twgut2+b6Li8NGKcUTv5s0pKamjoSyaW8hEvGAicpUVm1SRRO+Ox3AT+Xlnix8+umnkw7P20PL1q4ny7KY2WDvoUMi6TguL1q8+NBFi5YfAKC0ofG5W8KwWVlZSVBFMvlNaR1Gzx5qZIOmKL3GFU8dWFcbO0xrNh6n494jTaQUtGnTJpStXj2Mmf+5dbPbSCSig8GgvOKKM1Y9/vzjJ7723JdfL1y0qr/RWgspZMuXQnnAAtaOqxSrg/vsP+OOP9848phjjtmQDuO+V1w8gZ566mZ95pkX70y4yygltdYGJSUluin6/e1Fo5hZ9DrgGMFJosc0TQkRCARUJBKJ7Vxc3gNnbZHo5TQzIAbGtpUcPLjfpPPOHvnJEUccYU2dOjVRUlKCHbVuKyoqUPeFb3104qQfbpz0/cxWtlKmGU3R9shIsjzRfn7/x7VE59SQB0/2vF2vHGxLDBwDBHJYo87lLrM2rek4KLtTOQAzf/nyLvG4O4C1YSg0mo+mzcWvBtCiVSv/8jv/fOOEu267CZFIxOy+LAtR8/hbGdnZmZYXFm66vlAI0SxWsa2DOSlZOGXKgj5XXH390Y6jjc8HsTcZVkJKqtlUizVlZccnlY1p8Gqf8tvf5dfWxmBJn+C9SIYzG1jKNuvKN1ovvvjmMQBKI15tsN5tPm92tg0lZH0CtTmknGgEEZiq2Ym88caBVVW1liC5N61xPZ+oMYzy8nW9bNtqtEAxpTBvueaWtffff/cJhx564GIhII2BuxvuBwbaFRJq0MDe018Y+9CIc88duWFPN2/dAwQmjbVf4l9iAxjX5datspCZmf0BMyjr9NM5PeAameLisLEsVdGpU6fZfttCiyDiWngU5OUZAHxA+/aTpU7EhfCyPZREv4oUOYHwphAGQhhymI2x7XYLfl59eOqZfv3lpKNqo24WAWb75rRIGU3GtgUyMwOfCSESQFDuVZyMAIgc3j0HgBuVhc88858DNlRs8pO0kkku3qtkIRtg/boNPf1+f0NZaAD4V65Y3Z1ZePb8XibIhZBcWxPHqlWr8qQQiEQieyJA3HKGX6omi1meEK2NQ5DkdLUlkddvjpnd3TkB6Hg87jqu2zmRcLo1IB/eRmGGQiF18snHlT/6SPjqI484dKlxWLV0XzjD7BKx6j+w9/RXX3lyRL9+/TYkKfJ+LYryVzWIk7W3Phv77de6DgDnNT/Uidatc0Qqh0K8twkSYZiZju/du9QirFaWECTJUAP2nvop4LHukIFQZFxLckVt9bDUgfhp+k+5VZWboJTa4VE2zNSqVRYG9u/7CTMjWPj/7z5LyUJl2cNjUacZspBSoDBuXIZhq7lrsjCRcBxtuGMsFtsfAMaMGaMAYOxL7xzlasphrwUU7W1ejyAporE4otHoMZZtbRHBELsv6ZtEBHPLGYGLSkszNRFYpF/ErbVGPJEQypLKtqTyWZbyWbayLdXItLaajX2vsWkrKaTVrm226t6t8yIA60KhkNge0CKVwzz66EHFV+f/dkjfPl3mMCCZjUkJyWZBNLZi7mHWRgitDunbY9rDD943okePHhVJ1KvZp9Z2nznNECACbNuWO+1J6AQMCC55pBB7GVcvCoqKJBHFO/qtT1pl+uCCTYpsAcKbHkkBgwU8nlewiOkE1UEM42R4/eclZcdHa+ogRCMlQfX9MRlExNoYsV+rVlV/v/POaQDQb26/X17CMiXZp7xIfyJtYSyalxEA0BiN+sJFSzKNgUcwX8+qsS0zWIqFi1gCGnDiUbKUUpaSympUBjaUhQ3/LZVtiSZ+f/NUUlitc1pZbdvuNwvAGoDpjTdWMwBMKJroj0YTUojUfYm9LJSlQVLi5yUrXdd190CLrhYexcliqrVr1pp0WR6SCFDO8Fs05JijV7lOfFzciZPwqGNghGncGW6YJWImAQkBSp2JzSWCSaBifVk7G95//+41V1xx0b9SfSLRNKhD5+aG1MXXXLz2xRcLRz759NjPfy5ddSizZQyxAOnmkcBvXhcjhKT+h/Scdtcdfzp56NABFb+y0OuvfjDvfSFUtCSbD4DW2Rnv+CqqbhDkpeF4izKPbRoMUjwRByx7YBlzh3nz5ul1ZWsPNmCWjRnsycPF7Bl+UpDs3KnD4h59u5cBECkAGHYb/kDuTve8Rd5m5YpVxtVpgmMIYOOy7SPKGzp0jeu6/0vEE17sj1LUZ6bxvrT1dJWaBAAii7Zmzd7yawKz4e7dOkdHjDjhbiKKAiHRoUMJA8CCuXNNNBoDCbG3RWDr9YYggYqKSjLG/PqUZWrU1NagGU0WjOtqGnDEgFUfffDfgUS0cU/c45gxj6S8R5MGqs0dNeo56/e/z18zZ86cS4L5t0xZtqzCJ/2CGQ4RZPMSBcQcjzvo3fuAmonffngKEa1PNYPdp8L2DbQgm89ZfQbNWvFdcXW1QBtDSRJF2m5NKLEx0Iqy6xBv/dLY9wdHaxPZROQyWDVteGhulZOFjl06vROLxZGbmytaumRkGxUhBHZXzSq1kOMQjdVB0I5yN5zicTVxJ0GHDj5k3Yfvv3AYEa3ZE3vlxRcfT8XSTCTiUd9VVFdjr9SSDaInRIRYPLZNvfOvSln6bB9qapt1Tkhr1wFQnZubq2pqaigrK4vT25Q1BEx1mDkLQPdNcdTz3iaSr0h97QMQh5uVqRa5WjdD8BTKMWPyHWa2Tz7twmfK1633KUvC60Mqmg8FYJBlKV61anXmb3LPfpKZf9egyH/PhmAZ/2e9K/x/HW0mTvZvrWqlrKJKvzinJho1YjucpCmlw8SusS25fMP6oQsWlA7fVFkHaant5Kw8nkL2QLJSKlQN6Hf4C965LN79ERJj0qfmJC+o04w4bLMCRcyMLfjucgEUA5ZlAYiniZETIBIEjw6kEshVRxyRvixct66DKCmJJJg5AKDnpk2AbW+Wfw3lIhJxZGf7CMDPRBRLlV4Eg0AkArQKZKJmU/Ve2Ty7oeiybB/2CDdsi4/kBmnfoT0qKsvSb0XJbKoqq3q99dYHecXFxRMKCwspP3/HnbyDwULJHOQ77gr/efjIC2/w2b5eSZLTLRhFU9BuIQTi8Wjs+BPO/eGyy/LDv780WJSGghKRSL5mZt/QoadH5ixYnsvGGCGMF85vdovZJNcokYjHY2begiUX5p5wnmLmfCLCnlaYQgp7n2r5vzn6tW9PRMRvzZhaaHP8HC901aAclZLlqQ0koiQhahJ1tGrFmouXrlo9MFEXh8ywtlNfaZIekWBttOjSpePG2267tOr22y+jZpUR7YVDpBmG3Vw2YxoThWjfvj0qKlenAbJkgEnACL2xYlOXl1977yQg75M77+yfliwMhULi3nvvde+88/4/nDTy4luEbR/ADVT+tmFYZoJgKcXs5/4buQPAV6FQSKTKp3od2BPrKubD1EUh1N4ZimVj0Co7m4UQ0Nr8upRlaoP07XMQFi0s85oY76ACjZlhWxYvW74a33zz4x+I6Ou5c+eqNGn1+KuiH46ePHn2I99NmuHlMJokkWEAwhfI8OX5rQ/a2LY1uKm8Soq6j5n7X3TJLW/NKVkxAFJoKaVHpt1cYbAVGkgpS8Rj2imZt/T8ESdfWJhSmLuL3WVbAh+B6uq61f+HU3eNbgGR7BWqjfN/+7MWFRkAdHiH7K9X/LyhQliyrXCZjSQi9qjQWQgIk+w040kgIZRCyYyFI5euXAOyFTSZraqRG5TheF09TCDgE9277Pc5gERubq4kot2eUtA7hfxPNIczJi3PsqnaqQH9+mLx4gaykLZle0o10mIYWD7Bq1ZvwIcf/u9c4LmPxo3zGiek0bgC3377bY9bb//7EzNnLJcGpklJSEm4rW3Zh7pu9MlRV51/SDgc5hSG44TcXMwrWcYbKjaBpKhnpNprIicQ0NrBgft3sxcvtKB1/BfhFtrpkWLrSCSc8T6/BTaG0on+kyCRSGguKpo0orDws/5JcnPV1ObIz88ny1Lmzdci4VkzFpqsrCwnMzMTmVmZyNruzEJ2Vja7rqNramsCQsjt7vMGilJeeNH17//vq6IBBuwKQpJzlXa5XSszoKRlRaMJd/asBeefMOK8wqRFTjtuc7VrgBVmZimBxaWlc7U2lJub++t1A5pbEEoCjuNgw4bKPc3sv0dHOBw2wcJC0adLn3WtMvxTM3w2SHglJF6LLoIghiBOccZDAggYG5FX3jZ1m2pZKrndTU7J8K2rXcpplYU+Bx8QISLeHaw9LUbJbVktS8G1nQq81BrE47EJtk+ADdKQhQwSkLFEwsyaVXLOyy9/cNiYMWOcZKehJhRlkZBSmNfe+PjpxYtXSl+Gz8nKClBWE7IwMzPA2dlZYLCpqanNaHA8DAAMHjxoCuBWy/qal73rkRpmtm2FzEz/HNfVCAaD4lelLPv186DieSPzSrOy/I5hl9IJUjIzWZaPV67ekP2f5154l5l7JIlxRW5uSIVCIRUKTVChUEjl5uaqcDhshCD37tEPj54wYdJJjgsmEpYxBjuarnbYsoXo0KHtLNd10RgaNqmMNTNnDhly+geff/Zt74SjXaVItbQTZthASUtFo44ze9bC84/PPSvCnmtpdtzFfMshLWWnG/oiInJdB/369skTgv6/ci2FUFS9qQ6Oo08BwJ988sn/WYV5g8fmg7YZrb5tY/lgyLBXJiJAgiDJgIQByECzi5yMLMwvmorSGfNEViCT2GhIs33/iwADGBnI8C154N7RkwFQYWHhHnFDtNbNDNsB69ZvcNLlTeZdSP2nZOFZZ532c05OIG7YIdohFyzBGJClJMrXVLZ66cW3390Yje4/ZswYpylZSFTs3nv/03eM++qH0xNxaCJORxaS1potW4r27dvO9vlsDoVCoqCggAHQ8ccfVtWxU/syhk72Wt+7jogxLgKZPrTv2HG867ro14C2VP1KLFkGgKsvD8569aW31y9fWd65viVHGn41CWWmTJl78G/PuOyH19/6+PdXXXH+l8XFYeMhy8INlWu7K6780+1vvP7+nWvWVmifP1N6LbDSOmCckxOgAw7a/1vXdVNkx6ax0Osll930Ycm80gOFzDCSWDWnjyGaAYFmNhDStuKO686aXXreBRf9YQIzjyKihV4D1qZzFiX9vTKBNeXrpsZjMY97dcetUki7wOQfprYxhgURmVGjRlkLFnRm5AF5DaN5qP+32WtrQJvRkJYkibq6OM+ZPf/E+fNXDOrbt/usYDBkFxYWOOk0HS4sLKTrb7jzV6Es1+V5e6NrTuvxG1YtHy2IBLGXqWQYeK27CIIJmdKHeHk1PnvpffhcBdjesgre3KVkCxIRBjRrY1sQffscNJmI6gCo3R+CzQNQjDatWrEQAtxUs5tkH0tjSPt8GfLMk/MGPvvsrMW5uRDFxTC7GoZtmE5qSKQeDhcwEMa5554854mnny9bsqysl0e60jT9Z9LWFUJIM2XarP0vOPfKyW8UfvL7qy4//9PtyMLWV11z662vvfz2PWVlG4zts6XXVYzSk4WtM7H/Aft/l0g4HqyJyM3NzVVElLj40hu/nzN38cGuwybZcX2vKRvR2hXt2uXwiBOGf//Ev+7dwrf/taBhOTc3VwFIHHjQARNmzVl8kdZGE5FKx8MCQRD5TNGEnzqXrVr3xe8uvfmbAw7s/mHfQ/qtzMnJwezZs3nx4tLcE07MP2fevKVdqqpqjS8jUxp2kQ6LNhGxMVp26LBf4rLfX/7Jww+ORl4eTArmPWHCBDV8+HDNzL2uuebOcR999E0nktKF0EmPsplUlGn9getZscwQQipXsztu/MTcP/6pYBwzH0tEq1MKfLse/dy5DABdenRZFggEyJgNO+RaJUAAwixbunLw6L/9421mvoCIPGVR7OWeG47iLeWI2SvDq5yuN6/J58sws2cv8oXCD77IzOcS0TKicFr2FhHh2utu/1V44/mUrxEKiaFde0187vvxs+2A7zAT11oySy0kyBBgPE+zlZ2NV199DesXr0ZOIACHDQw1kZpnwLguWrXLRO+DD/ocAHJzQyguDu/Wz5SX55Vm9O/f3540eQ6Ya3d4/oWQXFcXhxC4ggjvFheHZW5uSOXlbfl7S5cuVXl5eViyrFrsKldUUhbqvof0LZoz9+crnJg2JNODz7N0hRDM3xZPbb+2rPKTCy/6w8QDe/f88OB+vZe1zm5Hc+fON4sXLTz+hBHnnz1/3vLuVVVVxuf3C82NdYVpXBa6rhbt2rZOnHv+eR89/kioXuHk5eWhuLgYQ48f+sWUqXN/v3zZWvh8fjD2mhJwQwTq0qVryemn5y3YugTwV1M6kpeXByIyr78zLjJl6pyLFy4shd+fsUVH8sZ4sxugtITlz+B5C5di8ZIVw9rt13ZY69atoZRCTU0NNm7ciE1VNRDS0rbfLw3r7R8T9ho/byaOJuOzpcwOBN46tO/+pQ17RBYWFsrhw4e7zKyGn3Du8zNnlXZihiOFspq0XMEgmCQLUgody8bRRliWZIJJsqFtr7PL5g4QzIBSSsViTuK119/vPn/+wmeZ+axkA93tomQLCgo4HA7ThWefEh3z1Nj1i0qxXzJ/T5vX2zTSgUWJyk1R89rbH54/dU7JN5dccfMLHTq2c51EAiQ2I7PYOJwVyKZhx/1m5mmnDZu1pwBI6Y7BfQfTB9njRVl51TbsMtsVGsTCGJgvv5p4+MhTLvvhL3f/86GTTjw6clRenkZtLWdmZjb6h8vWrRM927c3N9082gYbSCiYvVxthvLyRDgcNm2zsiZGFQ6rjUVZ1vdhNVDKRrbMxgfPvoEpn36LnEAm3GSXCUqStPFWNMDMDCbBTEa1ahXYeM2VV3zxzwf+gqKiAp2m0bHTo6TEK5y3AxlLWbMmKNKkm2hGTJCCVTweNUXf/HT6c8+/e+cN1+X/s7g4XF8PuaX1Clx7zW11CjrtSpPtyEJDRFxY+PF/vi2e+Lufl6wXfmUjrSgYE5gk+TJ8vGDRUixZtuK4Nm1yjmvTtk1SFtahomIjNm3aBCksbfsDUqcazG9nz1OyVaIhAWajbVupzh1zvh5+3KElQMN+uQUaCNMfrrnos8I3C39evnzt/iBhwFr8cqawd+8MwHFd065tazX0mMGfEpGzW/tZ7s5RUFCgw+GwuPi8E7/64J13Fi9e9POBHu9dw4XmJhLqDGYmn98PZujy8o1cVrYu5XlBKQXL55cMllyvKKnJfpbei0A8nkCv7u1x9lmnPltc9C62Dr2Wl8d6Dz8h+MTUGQtGMEtXWXIHijKlHFM8wwKGtRGCRedOrXldeQURqaRm4R0HfJKdESxl2YmEdn/6ac7pxw874y1mvqixjuANrUQvdENr888fNcPvzxhhjPHaIDeRZGU2sGxbrNtQbTZMnHpcVnbmcbZU21yBiaG1wTfFP+gXXyy8moheSrIN7RUe5tkXnuw+/uyYqDE6m8jaYe1dap8JKYTWxnw3cWqnkpIFj73//hcPtGr9GDMbEIznrWyVQWBoKKWwfn2lL1lhKImwVxerphpCtwpkF6+N19yok2eR2CAzMwemOo53/vsivot8iXYyEw6ZzR+7EWgHJc+VYRippGyVFZjSu3eXcgBy696C2I3YiCOHHjM9+4VCU75ukyUFsQfN3f5et302lS5dzU89NeYfI0dePDirVasJPXr0EI4TN95JFEjohMywM/TK5WuPdBJeideuAKwAiGDw9J/eefeTkiXLygdykn8M6eBxGTAw5PP7wMx63foqXrN2QwNZKGHbfsFgaZh3+Lb15XREiMfj1KNbB5x3/lkv/u+LQgSDwQZk5J5XTEQ1f/3rg+8tXLT6tupNMVdJEr8kOCuZq+NEvE4cdOAhsXvuuP6/o0f/aRt4lfo1FUOHQiFJRLVPPz/2gTlzF7+wZEmZ9tl2Epyu02p6mhR40rIULEtt8f10QZ9MxqOiYwEB0j5pycMOHzD1lluumlJZuUKEw2HNzIKINDP3u/rqv4ybOePnzmDpSilU2uBSlh5tn3ZcS5E6+JD9p955181//Pfjz787+Ye5nZSyNAktTbNQskoZ7bolJT8H8y+8riMzn0dE67fn1aWS83/960Of5EyfP2L9+gooJTfXcDXKMuStpWX5BBi6pjrObGKNKkuwcGuqfvZ/8smnZwJ4qby8nPYGtCcAqZQoyxt+3nSfTw5jYwxYyHTyK0nksfD5LK6sjpuKyqifl66t7yjfOI2hAcNASQWlLPwauAnnJp9oh7atpyxdXs227RdZSgGuwYIf5uGjsW9i5YxFaO3PATOlFW5jBoxxOTvLz/0H9vv2x++/QG5uLhU34qrtJmyEyDu6f2VGhponJA/yEDZNo9uYQX6fhUWLV/Cy5esuzMzMuFBOngXPOEqyyrMLEBCtc+F477hLCiLJPe2+8cYn/5i/aNkbCxYs0X5/QDQH/7BZFkrYttrci7YZsnBLfK/RljTi0IF95oy66uL3V69YKMLhLdM8eXl5pri4mO6++65/T50+58YJxT/atpXFxhja834lJc+igNaO7rBfazVkyNEvk9+/qGF08FeFht2agPyGq6986eCDD/jSskkxjAY3H6mf2hDN3xgNKiuJEI/VoVevjjp47vk3EpFTUlJCSbQp1zH3uOraP48rLPy4s6PhCmGp5l7LGO1KadThh/Wd8coLj5x6zuknTvrXYw8OP3booDWujkowa2omuo5IKccV7tcTfhh2xZV/Gs9JL2Y7i2iIiG+++Y8f9+jVSbtuTHhGsdhhZy3v4JEUQilpSSUtUtISyUn10/ZbXFldVQMAe0AmpjVyc3NJa0aHzh0n+DMsNtwwVczpGickFaRtS/Zl2N70+9jnT702nAH2+7NZKX9auLW94jwSmVCIxeDWnZaJ6sTbWBfFpA/G6zF3Pozn73gY62YtQ5uM1nAARCVvLaQbFbpelz4jsltl0NBjj/rWK5f4A+9BbIQgolj3Hp0m+yxiNkiLgJWZYfttYqF11aYqd8PGCndjZaVbUbnRrdhY4VZUVbobKje6cbfWQOr0S1IMY82abdnp7r33XjcUComLLvrtO8cc3W+iZZECWO8shs0YhjE7LwtJEOKxGu7ZsxOddeZJNxGRW1JSQo2WHQWDIhCgZSNH/uaRTh3biETC0b8cH77XlcrohDy4T/flD95/2x0ARGPI61+VskyFSoiIr73qousOOqhLTSxWCyHEHm63TSBIaNdxWrcOyKOPGvjweecN/yE3N1dFIhFdVARBRBz+2yM3ffppUWdDxpFWEvWadpkjwbBxQUYNHNBn5j//cd/IPn36rBs1apQ1aND+86+75ZKjDj642zzDkF47rnTY5TUADQZDSEvFYtr5/LPxA6+95uarvBBJSG5nc8tu3bJ+PvTQPu9l5wTIGKM9j1LtyNJMXtNtwETSMFNlwGCwUaSUX+xdOfIiAwAjTx7xbrv9WpPrupKo+b2YiQ3AmmC0V2lvvEYRZHiLCTbErIlTsvlXojCLigoEEfGr4SfnPXbd3fzmA2N54TdzEWAbPl8GEuzl9mX6QtgwG9GxfbulV19x4WQAFInk77Gw/B/+4CnmU046+a2OndqT67gibcYgNiA2UilSlpJKKbF5CktZwlYCskUKqlJKjYicq39/wfl9D+6z0QMa7fkqfyJCwnGcNm1aq6OOPOzJSy8NFnmc1I03b/CaSOSqO2+/4Z6BA/qNI5KKkaYMa+G+eiQY8VhUd+vaiU4YMex6IqoOBoONRtnEbm3wtwUZUsuFyEKhkDr11OFLL7jgnNsO7nOgrKuLahKCPdKPZLsgeG2uaFeFTrLdSOp9vdAhAV6/SCsvb+ic559/5N7c3FxVVFSkNxdFAHW1URdGgMhzKJlMsr1YY9nJ1Pum6qJcV0qowYcePPP28N0jjjyy7/pgMCjHjBnjBINBed5pp628846bTxjQv8c8ApQ2WoPq6a22s+bUIFHPYBZsWX60bd22awoNiMaJFIzravzxT9f9+aD9e25MxBJeXzxqGPqmJhLoqfys2GJSssWRV7Es9rIoBhkgJH5/ydklA/oe+K0QzAAbMDWvnzmLrWbqaW89m2Zlwl5LGOKBYg7s0mWRrHWolZ0tMgOZcAXDhUmGnZtSliZJ0+gpAGOM8fv93KVLl0+EoGhubu4ebfScRIeLa64JTth//+7fKqGIQXoLMNJ2ZUryHLCob+G1+Wva/L20a5Ga/uApWXjMMcesyb/w/Fv69ztA1tbU6M09Lk2DdAm3YJ/iFDjL61dqmFxJsAYf2nfyi2P/9TcgKIuKCvSOQEpaM4XuD1977JCBiUQ0qsCUxLSZZFqNW/zR18txMAQknJiTaN++lXX6GSPHFtx962dNKXmxFza6TzscO/quPz538km5D3fp2s6KxWOahNoihEUtcQ/1YB5PCREEBISOx2vViScOrXjwgb9fTkTRoqIik7JG8vLyDMB0/bXXPXn0UQOXgtnmZBVuY7eTEpj1qpO1KwSrIw4/ZOZbr98/4szhR65v2GYrEonoYDAo8/NPX3P/3687YcDAA0sEjASzu/mR8vYbwELAGONKqe1jjx286MGHQ08mG1Wb7ZJnBwtl727dVpx64gm3HnBgVxlL1GkScjvG0NYIZdGI8mxwEMi0dO/rFhmFhf2JiPTvLj7/3v79DhS10U0shUirnGiLtof1k7c7f60jFa4659LTJ2a3ya5NcIIS5Hgx6AbbbvsZqS0FojFGZGUHqNv+nd9h3qMh2IafiYiITz/n5Hu79+xIsWiUt+B0bfJ50fblSGruBln41zt+/8rJJw29r0f3zlYsFtNEgrlF+51sebbJ6zMDgHQ0WqNyhw/Z9ODf77qKiGoKC4PYEao9qejp6EE9f770srPPHDSoTyIeiwqCMLzF/bb0fXvIMiIJ13GdrIDfHn7CkM8effhvNxljmlTy4td6SCORiE44jnj04b/dMXz4kQ937tBGRWtqHCUkp5qhmhYQRFzvrUkISJBmNxGvkyeNHLrx7oJbT+7Vq820YGGhpAYsl95GKKB+/TqU3f/3ghOHDRu81OioZCM0bS90yZRESWqXoNWhh/ad8co7Y07s2rXv+lAoJLa2dlIKc/jw09f89Y4/ntivb68SMkLBwN3Sq9/SKiQAbMiFNmrkiGMWvVL43IlEtKGgoICaIgaIRPJNbm6uuv8fd7107NBBz2UHLOVGjePJEL1bogi/9MjPz9fBYFAGg2eOO2xwv8fbtclUjhNzSQjsG1sgpnHBmWcs79evz1IiJkHNCQXSFpSwWruiY/vWmx57YHSJp7iC5pd57oXy5usuHZeXd8RrbXKylJtwHQGxV4bHI5GIdh0t//ng30afkHfs3zt3bqvqamtdSbYBq61SP7zLoBiwAJEENLmJaFyOOPHomr+M/vMphx3Wf+6OarcbS/Fcfsn5X55z1mlnHNKvVyJaVyOIlSZYLXzfXC/HJUl2Ewk3M0Navxk2+POXX/jXOUQUZa/dE/+fU5apyP2wYcPUKy88eUfw3NMfGtDvQCtaW0UwRrds+JsgBLEbr9NCuOrss0auvv8f9550xKBDpoRCE1Skkc0RDodNYWGhHDSo58/3Pjh6xHFDD1sG40hu7N44RR7tulJoNWjgQTMeefq+Ed1ycjYkUVlme4ckGAzK008fvubWP11/4iF9e5YQacXsuttviO26bBJqxInHLnr9lbEnBohWFBYWyjQYdLioqEjH43F69cV/X3fOWadNyg4oKx6POkI0LARo4YXfCzwnx3HEs888dOfw4UN+tCyohJtwPKt6XxcyAAgGg7KuLkqdO7d/NTszA0Zvv0J0awAJ8+b6aGZj/H4ft2/f+isp5Tp4JSP8SzTdLiwMGsdxxNNPPnjTcUMP/1GSa7HWLhHtsadOQHMANzo3N1eNHfvwPeef99v7Dh3Yx6qr2ySYtbvlEtKu4zUEOJGo04SEOvOMEWsf+kfByccdfsikUCik0lWUDWXYqFGjrL/+9Q//u+6ay8/IHXZk3OiYdNy4S9Tww1MLYU1Yx6M1aNc2oH572vCP34v89+xkTaXY0V77lStL4uLiIq21kY8/PvrO62+4/PJjjz10vaWEdBIuA0LvStKYiEAkWWt2Y3Ux6tGjs7zowjM/f+P1pwYNOqTnFE+RDXebslALCwvlkQP7lD7wcPjEvNwjlzE70hhscV8kPEUpJKvDDu8/4/HHHhp5TL9+GxqGXpvabMFgoczPP33N7bffMGLAwANKGKQMwyXamsqJXcOsRp587OKxLzwxIhDwFGW6GzxJSIAzzzxLPvufB08YMXLImG7dOlt1sToCWLd0gp6IjNm6XfkvU7IEInLefO0/J+XlDfkxI+Cz4vGEuzOAn//LHma/QX0/a5UdcF3XpfRBMZvz3cZoygj4qFu3bu8YY5CbG6Jmtr+ydsNzr3z3nedOGjr00B+lZJVIOE5DYo29aRQXF7vGsHzskbtH33zLlRcde9yha5UPKu7UwUOZiZ1WOkQEIQRrw240Wkvdu7eXl1x61ri33/r3oIEDe09KGvU7RUc4ZswYJzc3V1177UX/e/LxB4eeelru923bZalYopYMa5dIMGHX5DhI6ISjjTFGDhhwsL7ggtNvf/31p88kIoeZkQ7d5m5Rlo7jkCCAUsnl+rBg05OIwbq5vCXEALTjuHLUVRe+8tkn7x5+5tknRbp0zWHAlbF4DK52Xa8anLhBo7gGnoFXFeApR0opBe04CR2PRalVtk8dP+zwFVdfffm5L7zwr9OIaEMoxGJHiiylMEOhkDpyYJ/SB+8Pnzgs7+jl2iSkMewhSknAGO0SGXX44H4znvn34yM9ME+hTOf9kyFSHQwWyvPOO7Xs1r/cOuLQAb1LBKCMgetZUwStjSuY1WknDV/835efOLFt28Dy5ijKhkKksLDQEFG8sHDstVdc8bv7+vTuVSkFy3gszsbAJSLjrWOqQm17z1wgdX8Ne/WEQp6QXL2++pCu3bp2TSQSTCIFd2hqAjAtT5nnhdWZiKjqvXfGnnzKKcPf7tC+lYrH60gb7RIJQ/W0uXtqbgZuCEH0S3rhKRKJG0ddMr9jh/YrU3bOZoBJE5N00nsSbNjINm0yqy679qJxnvAvaNberKqsXCnrPf409kqSFavpMGGhJKKqzz978+QzzjyxqH37bCsejZHWxiXyyqq2XPmGucmtZB+l+5rKcQLGaNOQGzY9mmotL7vkvLeKvio87KwzT3qzW5f9NMAyFk9AuyZ1Pjl1NnkLEBDXA65AAiAyDNYJJ6Gj0TrKybTVcccdvvrKy393wUtjHx9JROXNkVVNKfpgMCj79es1rfDN/xx/+WX59/Trd8AG2xIqHo9TwtEukLrvZCSiieeaunfDrOPxBMN1ZYe2WeKkEcO+uSd817BHHgo9kkgkRLImOi2ds1tICexsfzxWF3WhDYzxCKwaR6Vyg/+T4yQcCtjWzjYN1rm5IRUI0AohKP+x/zx71BcfFd++cvWG89ZvqFTV1TVwHQ0pLUOAkVu1L00i8WCMliBDfr9Ptm/fHj26d1x56OA+Tz7+yH1jiajCyxEzqBl5mXA47BYWFsqBA3uWzl648IRbbx49fuLEGT0AOwEBVoJ9gwcdPDMcuuukvn27rk+H5LxxhRmU552aW/b5u++OCD3y4tfz5i8/hDUSmg1A2j7xhKGLX37uvhMDgZ1TlFt5mERE9Jfbrx79/fffv/rUv199aPachWeXr69WNTW1YMMspDRE4O15GR7vKjuJRJyUlJkAvOalqX2UITfVbNqUALPF2mNgapQzh9kLkzsuCYFAp06daHegY5OhmkopxYW33XbPR99NmvHokmVrOlVsrAYbw1JILaTcpqvgbgjOpfJHxhiI2tq6OJJ0ar9UPiQYDErLspzLr7x16qzZC3pplxJSSssjW2y4CNyg1yLDCMNgRWyEQxSX+7XPGT/8qCPXeWwXzWPtyfT7OzhOwrCxHFDT8Uuj2THalZayMnZ0rlLPPRDIGP6X0f+47eMPv/7z8hXlnaqrq70+plJ5jBKbwewN0itcj6jfXBK0I9nsCXDHcUTrbCsw5Mwh9NprrzVbFhJRGREufvrplx/++NNxt69avTZ/3fpqTxa6LqQQBoARUm4TKjdGQ0NLKYSwLYn2HdugW9cuZUcMPPipx56873kiWt9AFuqWyr2myFwA/H3KlJKxjzz21PWLfl5xw/p1le0qNlQh4boelYAgLeqtcaoPVxtjwDCkjRZSkAhk2OjWpSO6dmxffMxRgx597Il7P3733aeRZFNpVjRsd1ijQillTjrpgu9mzFx0nOuaJvlPU4z4rqvRvXtXnPXbYZeE/37HG7m5uaq4uNjdifojSlJJaSEIn33249Eff/rpOfPmlQyLRRND1q+rFI6jEY3GUd9OjQhKSfh9FrJzMtF+vzZr92vf7utDBw/+8M7brhyXVJJIJyyaRmNpPXv2wgPvuvvv46dMmdWDSOLggw+a+a+H7xx5+OGHr9sZRbl1/igSiej//veNLi++9Na40tI1hwjBOObYAaX/HvPoCV3btt0lRYlti/dVcXGxK4XAh59NGPrpx5//rrR0xakVFZW9KjdWw3EM3FTNMW0dgdPQOo7OnTri7LNPua1g9J8fTb6fTj5Lf/CCq2d89+30PsaI7TD/phiDANu2cPQxB094750XTykoKHC9Dg0tCz9suL+Yeb+773501Lz58y5ftmxFn6oqF9G6OjhbpIxpt/BZEiS0cZGVlYkhxw5+9603njofCEogon+pvGUkEtGF739yxJNPjP1hypRFitlANMjxpQhABIn61lOCtMfNaQwOPLALTjl12AWPPhSOBAsLRSTNPZo6M088MeamV19978mff14L22fBNBGkMsZF9x7tcc55Z5wx+q83fbKjs5187qnUaLu/P/Dctd9++92FpYtLD45FXdsYgmFuNKxBjaZ3RBNikWGYYds2jj7y4PHvvvPfU739HG5WLcXWsvDbbycf9sEnX18xr2TxievKyw+uqKhSTkIjFkuAzWaiFWUp+H0+ZASAnJzsxd27dZt66KEDPrjzzuu/JqJ1LSEL091PAFBeXt55zNi3LyspKT1z5fIVh2zYsLFNbW0ciYQL7ZrNbZCI4PPZsG2gdetMdOjYflHXrh2+GzTg0OfvuOPa76PRGACIUCiEnelytDuUJQHgWbNKOz788GOXrF1bkeXFe7cHIzNgJmP5fOL4445b8de7b3ghmfPgXaWDCofD9fx+Pp+Nn35a0Ldo3Phum2rrhs4pKcHGDRvJAPDbPu7RqycdcECPyv3371589tknrZCCNqTOWqqGsiVIvlOKas2aygNGF9x7aTSaMP988IFnu3Rpta6lNmDqfUpKSjr//d5nRrVu3QqPPHb3i7vqUaa71swc+PTToj6zS+YO3lhR3XPFshUspaStJQmTMZalxKGHDlpx663XvGCMafjcCQBPmPBDt1deeeviVSvK/EIJeDyd29Jguq7mgw46wL31tqv+3adPn+rdTcre8Fkxs/r006IBpYuW5s1bsCBn6dJlbIwmsVuyHCZlkiKRiPGAAQP4nnvuHNu+febqX5qIPnX9sS+/l/vVuKI/C6CLNgbJhovQWsNr2dSAzcckOMMXoA0b1i/pP7D3pMcfffDfRJTYmWvbtsV33fXAOTNnlgyKx6OGuHHOUc3a5OTkiP6D+k4Pj77to+asW8Pn7vf78Mwzr/f++usJXbOysoaVrV1LbsKr3hJCQEA0mujKyspCVlYWbGUnfy4gGrzG43F2XYMuXbusKbjnxleJKLo9/uZmnE9K1WdlZPgxbVrJwZ9/Pq5rbW30NyUl87FxYxUZY+D3+7hbj+50QK9em1q18o+/5ppLSqQUiZThEQwGZTINw3tmP+WLlAHo89mIxeKdX3zx7c5r164/sbR0aWDN6rXsug4BgD+QwYMGDaScrMySwYP6LTzh5N/MFYLcFH9DMBgUu1PB/+pHKMQiNzekdsIwkMFgoeTdwD3WWPPllr5OY+/X3KbPO/O5ku2DfpXI151Z4134vP9XhwAApSQCgQxkZPgRyPAjY+vp96bf70NGhj/JN4xfikm72c89GAxK/Opk4U6fz90mC9Nd71Bop2R48t5b5lnR7vyAeXkFMsVmgzTbcO0soirdzVJS0p/69ZtLRUVAw3vLq6evKTAFBeDdbTmFQiGRbBCdbD/U8tdLPYPkR9tjDZaZmQoKQEBB8vPtuI/g9p775nUqSqt57+5ay3Q/79b7CnugdV1BwZ7/zGmERZtLvyJCoRDt6vkPBgtlefnTlB77UAfeVU/DkyklVF7ej9J/7nlNfpk6L3l52G3PNnXf/fr1o233bB4ayAzem2qkvLNWQAAaPWt5eXkoKenP/foFORwm3lfftW/sG/vGvrFv7Bv7xr6xb+wb+8a+sW/sPeP/Aeus6wXndYjBAAAAAElFTkSuQmCC';

function doPost(e) {
  try {
    var jsonPayload = null;
    try { if (e.postData && e.postData.contents) jsonPayload = JSON.parse(e.postData.contents); } catch (err) {}

    if (jsonPayload && jsonPayload.action === 'submitScript') {
      return handleSubmitScript(jsonPayload);
    }
    if (jsonPayload && jsonPayload.action === 'emailPortalLink') {
      return handleEmailPortalLink(jsonPayload);
    }
    if (jsonPayload && jsonPayload.action === 'createScriptSheet') {
      return handleCreateScriptSheet(jsonPayload);
    }

    // Main brief submission - now sent as a JSON body via fetch() so the
    // frontend can actually verify success (see finalSubmit() in
    // index.html). e.parameter is kept as a fallback for any old cached
    // frontend still doing a plain form POST.
    if (jsonPayload) {
      return handleBriefSubmission(jsonPayload);
    }
    return handleBriefSubmission(e.parameter);
  } catch (error) {
    Logger.log('ERROR: ' + error.toString());
    return ContentService.createTextOutput(JSON.stringify({
      success: false,
      message: error.toString()
    })).setMimeType(ContentService.MimeType.JSON);
  }
}

function doGet(e) {
  try {
    if (e.parameter.action === 'getSubmission') {
      return handleGetSubmission(e.parameter.token);
    }
    return jsonOut({ success: false, message: 'Unknown action' });
  } catch (error) {
    return jsonOut({ success: false, message: error.toString() });
  }
}

// -- BRIEF SUBMISSION (existing logic, extended) ---------------
function handleBriefSubmission(data) {
  Logger.log('Request received');
  Logger.log('Data: ' + JSON.stringify(data));

  if (!data.email) {
    throw new Error('Email is required');
  }

  const sheet = SpreadsheetApp.openById(SHEET_ID).getSheetByName('Sheet1');

  // Always (re)write row 1 with the current header set - not just when the
  // sheet is empty. A stale header row left over from an earlier version
  // of this script (different columns) meant this never ran, so data kept
  // landing in the right columns with no labels above most of them - and
  // findColumnByHeader(sheet, 'Portal Token') always came back empty since
  // that literal header text was never written, which is also why magic
  // links couldn't find a client's existing submission.
  const HEADERS = [
    'Timestamp', 'Email', 'Full Name', 'Company', 'Project', 'Brand Method', 'Font',
    'Characters Style', 'Character A Gender', 'Character A Age', 'Character A Ethnicity',
    'Character A Accent', 'Character A Clothing', 'Character A Notes',
    'Character B Gender', 'Character B Age', 'Character B Ethnicity',
    'Character B Accent', 'Character B Clothing', 'Character B Notes',
    'Background', 'Scene Notes', 'Title Screen', 'Music',
    'Script Title', 'Script Method', 'Deadline',
    'Portal Token', 'Status', 'Client Folder', 'Full Data'
  ];
  sheet.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS]);

  var token = data.portalToken || Utilities.getUuid();
  var clientLabel = data.companyName || data.projectName || data.fullName || 'Client';
  var tokenCol = findColumnByHeader(sheet, 'Portal Token');
  var existingRow = tokenCol !== -1 ? findRowByColumnValue(sheet, tokenCol, token) : null;
  // Re-fetch the same folder by row on repeat submissions (edits) instead of
  // matching on name - the folder is now named after the client only (no
  // token suffix), so a name lookup would create a duplicate if the client
  // changes their company name between submissions.
  var folder = (existingRow && getFolderFromRow(sheet, existingRow)) || createClientFolder(clientLabel, token);
  saveUploadedFiles(folder, data, clientLabel);
  generateBriefDocument(folder, data, clientLabel);

  const row = [
    new Date(),
    data.email || '',
    data.fullName || '',
    data.companyName || '',
    data.projectName || '',
    data.brandMethod || '',
    data.font || '',
    data.charStyle || '',
    data.c1gender || '',
    data.c1age || '',
    data.c1eth || '',
    data.c1accent || '',
    data.c1clothing || '',
    data.c1notes || '',
    data.c2gender || '',
    data.c2age || '',
    data.c2eth || '',
    data.c2accent || '',
    data.c2clothing || '',
    data.c2notes || '',
    data.background || '',
    data.sceneDesc || '',
    data.titleScreen || '',
    data.music || '',
    data.scriptTitle || '',
    data.scriptMethod || '',
    data.deadline || '',
    token,
    'Brief submitted',
    '',
    JSON.stringify(data)
  ];

  if (existingRow) {
    sheet.getRange(existingRow, 1, 1, row.length).setValues([row]);
  } else {
    sheet.appendRow(row);
    Logger.log('Row added to sheet');
  }

  var targetRow = existingRow || sheet.getLastRow();
  setColumnFormula(sheet, targetRow, 'Client Folder', '=HYPERLINK("' + folder.getUrl() + '","[Folder] Open Folder")');

  // Legacy: if a script sheet URL happened to arrive with the brief itself,
  // still link it (kept for backwards compatibility with the old flow).
  if (data.scriptSheetUrl) {
    setColumnFormula(sheet, targetRow, 'Script Sheet URL', '=HYPERLINK("' + data.scriptSheetUrl + '","[Script] Open Script")');
  }

  sendSlack(data, folder.getUrl());
  sendClientConfirmationEmail(data, data.portalLink);
  sendTeamNotificationEmail(data, folder.getUrl());

  return jsonOut({
    success: true,
    message: 'Form submitted successfully',
    token: token
  });
}

// -- SCRIPT SUBMISSION (separate step, same row via token) -----
function handleSubmitScript(payload) {
  const sheet = SpreadsheetApp.openById(SHEET_ID).getSheetByName('Sheet1');
  const tokenCol = findColumnByHeader(sheet, 'Portal Token');
  if (tokenCol === -1) return jsonOut({ success: false, message: 'Portal Token column not found - submit a brief first.' });

  const row = findRowByColumnValue(sheet, tokenCol, payload.portalToken);
  if (!row) return jsonOut({ success: false, message: 'No submission found for this token.' });

  var folder = getFolderFromRow(sheet, row);
  var clientLabel = getColumnValue(sheet, row, 'Company') || getColumnValue(sheet, row, 'Project') ||
                     getColumnValue(sheet, row, 'Full Name') || 'Client';

  var scriptLink = '';
  if (payload.scriptInputMethod === 'write' && payload.scriptText) {
    var doc = DocumentApp.create(payload.scriptTitle || 'Script');
    doc.getBody().setText(payload.scriptText);
    var docFile = DriveApp.getFileById(doc.getId());
    if (folder) docFile.moveTo(folder);
    scriptLink = docFile.getUrl();
  } else if (payload.scriptInputMethod === 'upload' && payload.scriptFileData) {
    var file = folder ? saveBase64File(folder, payload.scriptFileData, payload.scriptFileDataName || payload.scriptTitle || 'script-upload', clientLabel) : null;
    if (file) scriptLink = file.getUrl();
  } else if (payload.scriptInputMethod === 'sheet' && payload.scriptSheetUrl) {
    scriptLink = payload.scriptSheetUrl;
  }

  setColumnValue(sheet, row, 'Script Title', payload.scriptTitle || '');
  setColumnValue(sheet, row, 'Script Method', payload.scriptInputMethod || '');
  if (scriptLink) setColumnFormula(sheet, row, 'Script Sheet URL', '=HYPERLINK("' + scriptLink + '","[Script] Open Script")');
  setColumnValue(sheet, row, 'Status', 'Script submitted');

  return jsonOut({ success: true, scriptLink: scriptLink });
}

// -- SCRIPT SHEET CREATION ("sheet" method, before submitScript) --
function handleCreateScriptSheet(payload) {
  const sheet = SpreadsheetApp.openById(SHEET_ID).getSheetByName('Sheet1');
  const tokenCol = findColumnByHeader(sheet, 'Portal Token');
  if (tokenCol === -1) return jsonOut({ success: false, message: 'Portal Token column not found - submit a brief first.' });

  const row = findRowByColumnValue(sheet, tokenCol, payload.portalToken);
  if (!row) return jsonOut({ success: false, message: 'No submission found for this token.' });

  var folder = getFolderFromRow(sheet, row);

  var ss = SpreadsheetApp.create(payload.sheetName || 'Script');
  var scriptSheet = ss.getActiveSheet();
  scriptSheet.setName('Script');
  scriptSheet.appendRow(['Line #', 'Speaker', 'Dialogue', 'Visual Notes']);
  scriptSheet.getRange(1, 1, 1, 4).setFontWeight('bold');
  scriptSheet.setColumnWidths(1, 1, 60);
  scriptSheet.setColumnWidths(2, 1, 140);
  scriptSheet.setColumnWidths(3, 2, 320);

  var ssFile = DriveApp.getFileById(ss.getId());
  if (folder) ssFile.moveTo(folder);

  return jsonOut({ success: true, sheetUrl: ss.getUrl() });
}

// -- PORTAL LOOKUP (magic link revisit) -------------------------
function handleGetSubmission(token) {
  if (!token) return jsonOut({ success: false, message: 'Missing token' });
  const sheet = SpreadsheetApp.openById(SHEET_ID).getSheetByName('Sheet1');
  const tokenCol = findColumnByHeader(sheet, 'Portal Token');
  const row = findRowByColumnValue(sheet, tokenCol, token);
  if (!row) return jsonOut({ success: false, message: 'Not found' });

  const fullDataCol = findColumnByHeader(sheet, 'Full Data');
  var data = {};
  try { data = JSON.parse(sheet.getRange(row, fullDataCol).getValue()); } catch (e) {}

  return jsonOut({ success: true, data: data });
}

// -- BRANDED EMAIL TEMPLATE --------------------------------------
// Shared HTML shell for every client-facing email - logo header, Textra
// brand colours, a portal-link CTA button. Images embedded via cid: (not
// a data: URI) since Gmail webmail and others strip inline data: images.
function textraLogoBlob() {
  return Utilities.newBlob(Utilities.base64Decode(TEXTRA_LOGO_BASE64), 'image/png', 'textra-logo.png');
}

// Renders "Write Your Script" / "View My Data" as real buttons rather than
// plain links - a two-column table (not flex/inline-block) since that's
// the layout Outlook and other email clients actually render reliably.
// Falls back to a single full-width button if only one link is present.
function secondaryButton(href, label) {
  return '<a href="' + href + '" style="display:block;box-sizing:border-box;width:100%;padding:13px 12px;background:linear-gradient(135deg,#1A71B1,#66BCAD);color:#ffffff;border:none;border-radius:8px;text-decoration:none;font-weight:bold;font-size:14px;text-align:center;">' + label + '</a>';
}

function secondaryButtonsRow(scriptLink, folderUrl) {
  if (!scriptLink && !folderUrl) return '';
  var cells = '';
  if (scriptLink) cells += '<td style="padding:4px;width:50%;">' + secondaryButton(scriptLink, 'Write Your Script') + '</td>';
  if (folderUrl) cells += '<td style="padding:4px;width:50%;">' + secondaryButton(folderUrl, 'View My Data') + '</td>';
  return '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:14px;"><tr>' + cells + '</tr></table>';
}

function brandedEmailHtml(heading, bodyHtml, portalLink, ctaLabel, folderUrl, scriptLink) {
  return '<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f7f9fc;font-family:Arial,Helvetica,sans-serif;">' +
    '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f7f9fc;padding:32px 16px;">' +
    '<tr><td align="center">' +
    '<table role="presentation" width="480" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(13,27,62,.08);max-width:480px;">' +
    '<tr><td style="background:linear-gradient(135deg,#eaf4fb,#e9f8f4);border-bottom:1px solid #e2e8f0;padding:28px 32px;text-align:center;">' +
    '<img src="cid:logo" alt="Textra Video" style="height:32px;display:inline-block;border:0;">' +
    '</td></tr>' +
    '<tr><td style="padding:32px;">' +
    '<h1 style="margin:0 0 16px;font-size:20px;color:#0d1b3e;font-family:Arial,Helvetica,sans-serif;">' + heading + '</h1>' +
    '<div style="font-size:14px;line-height:1.6;color:#334155;">' + bodyHtml + '</div>' +
    (portalLink ? (
      '<div style="margin-top:28px;">' +
      '<a href="' + portalLink + '" style="display:block;box-sizing:border-box;width:100%;padding:13px 12px;background:linear-gradient(135deg,#1A71B1,#66BCAD);color:#ffffff;text-decoration:none;border-radius:8px;font-weight:bold;font-size:14px;text-align:center;">' + (ctaLabel || 'View Your Project') + '</a>' +
      '</div>'
    ) : '') +
    secondaryButtonsRow(scriptLink, folderUrl) +
    '</td></tr>' +
    '<tr><td style="padding:16px 32px;background:#f7f9fc;text-align:center;font-size:11px;color:#94a3b8;">Textra Video - studio-quality animated videos, fast.</td></tr>' +
    '</table></td></tr></table></body></html>';
}

// -- EMAIL PORTAL LINK (manual "Email it to me" button) ---------
function handleEmailPortalLink(payload) {
  if (!payload.email || !payload.portalLink) {
    return jsonOut({ success: false, message: 'Missing email or link' });
  }
  MailApp.sendEmail({
    to: payload.email,
    name: 'Textra Onboarding',
    replyTo: 'onboarding@textra.video',
    subject: 'Your Textra Video project link',
    body: portalLinkEmailBody(payload.portalLink),
    htmlBody: brandedEmailHtml(
      'Welcome to Textra Video!',
      'Here is your project link - bookmark it, no password needed. Use it any time to check progress or write your script.',
      payload.portalLink,
      'View Your Project'
    ),
    inlineImages: { logo: textraLogoBlob() }
  });
  return jsonOut({ success: true });
}

function portalLinkEmailBody(portalLink) {
  return 'Here is your link to return to your Textra Video project any time:\n\n' +
         portalLink +
         '\n\nBookmark it - no password needed. Use it to check progress or write your script.';
}

// -- CLIENT CONFIRMATION EMAIL (automatic, on brief submission) -
function sendClientConfirmationEmail(data, portalLink) {
  try {
    if (!data.email) return;
    var greeting = data.fullName ? ('Hi ' + data.fullName + ',') : 'Hi,';
    var scriptLink = portalLink ? (portalLink + '&step=script') : '';
    var body = greeting + '\n\n' +
      'Thanks - your Textra Video brand brief has been received. Our team is already on it.\n\n' +
      (portalLink
        ? 'Bookmark your project link below - no password needed. Use it any time to check progress or write your script:\n\n' + portalLink + '\n\n'
        : '') +
      'We will be in touch shortly.\n\n- Textra Onboarding';
    var bodyHtml = greeting + '<br><br>' +
      'Thanks - your Textra Video brand brief has been received. Our team is already on it.' +
      (portalLink ? '<br><br>Bookmark your project link below - no password needed. Use it any time to check progress or write your script.' : '') +
      '<br><br>We will be in touch shortly.';
    MailApp.sendEmail({
      to: data.email,
      name: 'Textra Onboarding',
      replyTo: 'onboarding@textra.video',
      subject: 'Your Textra Video brief has been received - ' + (data.companyName || data.projectName || data.fullName || 'New Project'),
      body: body,
      htmlBody: brandedEmailHtml('Welcome to Textra Video!', bodyHtml, portalLink, 'View Your Project', null, scriptLink),
      inlineImages: { logo: textraLogoBlob() }
    });
    Logger.log('Client confirmation email sent to ' + data.email);
  } catch (e) {
    Logger.log('Client confirmation email error: ' + e.toString());
  }
}

// -- TEAM NOTIFICATION EMAIL (optional, internal) ----------------
function sendTeamNotificationEmail(data, folderUrl) {
  try {
    if (!TEAM_NOTIFY_EMAIL) {
      Logger.log('TEAM_NOTIFY_EMAIL not configured - skipping team notification email.');
      return;
    }
    var body = 'New Textra Video brief submitted.\n\n' +
      'Name: ' + (data.fullName || 'N/A') + '\n' +
      'Email: ' + (data.email || 'N/A') + '\n' +
      'Company: ' + (data.companyName || 'N/A') + '\n' +
      'Project: ' + (data.projectName || 'N/A') + '\n\n' +
      'Client folder: ' + folderUrl;
    MailApp.sendEmail({
      to: TEAM_NOTIFY_EMAIL,
      name: 'Textra Onboarding',
      subject: 'New Textra submission - ' + (data.companyName || data.fullName || 'Client'),
      body: body
    });
    Logger.log('Team notification email sent to ' + TEAM_NOTIFY_EMAIL);
  } catch (e) {
    Logger.log('Team notification email error: ' + e.toString());
  }
}

// -- SLACK -----------------------------------------------------
function sendSlack(data, folderUrl) {
  try {
    if (!SLACK_WEBHOOK) {
      Logger.log('Slack webhook not configured (Script Properties -> SLACK_WEBHOOK) - skipping notification.');
      return;
    }
    var nameVal = data.fullName ? data.fullName : 'N/A';
    var emailVal = data.email ? data.email : 'N/A';
    var companyVal = data.companyName ? data.companyName : 'N/A';
    var projectVal = data.projectName ? data.projectName : 'N/A';
    var spreadsheetUrl = 'https://docs.google.com/spreadsheets/d/' + SHEET_ID + '/edit';

    var textMsg = 'Name: ' + nameVal + '\nEmail: ' + emailVal + '\nCompany: ' + companyVal + '\nProject: ' + projectVal +
      '\n\n<' + (folderUrl || spreadsheetUrl) + '|Client Drive folder>  |  <' + spreadsheetUrl + '|Master spreadsheet>';

    var message = {
      text: 'New Textra Submission',
      blocks: [{
        type: 'section',
        text: { type: 'mrkdwn', text: textMsg }
      }]
    };

    UrlFetchApp.fetch(SLACK_WEBHOOK, {
      method: 'post',
      payload: JSON.stringify(message),
      headers: { 'Content-Type': 'application/json' },
      muteHttpExceptions: true
    });

    Logger.log('Slack notification sent');
  } catch (e) {
    Logger.log('Slack error: ' + e.toString());
  }
}

// -- DRIVE FOLDER HELPERS ----------------------------------------
// Client subfolders are internal only - never shared with the client (no
// addViewer, no Drive "shared with you" notification email). The client's
// only view into their project is the portal page and the Google Doc/Sheet
// links we choose to surface there; the raw Drive folder stays internal,
// visible to the team via Slack.
const ROOT_FOLDER_NAME = 'Textra Onboarding - Client Briefs';

// Named after the client only - no token suffix - since that name is what
// shows up in the confirmation email subject. The token still identifies
// the folder unambiguously via the sheet's "Client Folder" link (see
// handleBriefSubmission), so two clients sharing a display name is
// cosmetic only, never a lookup collision.
function createClientFolder(label, token) {
  var root = getOrCreateRootFolder();
  var folder = root.createFolder(label || 'Client');
  folder.setDescription('Textra portal token: ' + token);
  return folder;
}

function getOrCreateRootFolder() {
  var it = DriveApp.getFoldersByName(ROOT_FOLDER_NAME);
  if (it.hasNext()) return it.next();
  return DriveApp.createFolder(ROOT_FOLDER_NAME);
}

function getFolderFromRow(sheet, row) {
  var col = findColumnByHeader(sheet, 'Client Folder');
  if (col === -1) return null;
  var formula = sheet.getRange(row, col).getFormula();
  var match = /"(https:\/\/drive\.google\.com[^"]+)"/.exec(formula);
  if (!match) return null;
  var idMatch = /\/folders\/([a-zA-Z0-9_-]+)/.exec(match[1]);
  if (!idMatch) return null;
  try { return DriveApp.getFolderById(idMatch[1]); } catch (e) { return null; }
}

function generateBriefDocument(folder, data, clientLabel) {
  try {
    if (!folder) {
      Logger.log('generateBriefDocument: folder is null/undefined');
      return null;
    }
    const docTitle = 'Textra Video Brief - ' + clientLabel;
    const doc = DocumentApp.create(docTitle);
    const body = doc.getBody();
    const para = body.clear().appendParagraph('');

    body.appendParagraph(clientLabel).setHeading(DocumentApp.ParagraphHeading.HEADING1);
    body.appendParagraph(data.projectName || '').setForegroundColor('#666666').setFontSize(12);

    body.appendParagraph('').setSpacingAfter(12);

    // Contact & Project
    body.appendParagraph('Project Details').setHeading(DocumentApp.ParagraphHeading.HEADING2);
    if(data.email) body.appendParagraph('Email: ' + data.email);
    if(data.phone) body.appendParagraph('Phone: ' + data.phone);
    if(data.deadline) body.appendParagraph('Deadline: ' + data.deadline);
    body.appendParagraph('').setSpacingAfter(12);

    // Brand
    body.appendParagraph('Brand').setHeading(DocumentApp.ParagraphHeading.HEADING2);
    body.appendParagraph('Method: ' + ({website:'Website extraction',manual:'Manual entry',guidelines:'Guidelines uploaded'}[data.brandMethod] || data.brandMethod || 'Not specified'));
    if(data.font) body.appendParagraph('Font: ' + data.font);
    if(data.tagline) body.appendParagraph('Tagline: ' + data.tagline);
    body.appendParagraph('').setSpacingAfter(12);

    // Characters
    body.appendParagraph('Characters').setHeading(DocumentApp.ParagraphHeading.HEADING2);
    body.appendParagraph('Style: ' + (data.charStyle || 'Not specified'));
    if(data.c1gender) {
      body.appendParagraph('Character 1:');
      if(data.c1gender) body.appendParagraph('  • Gender: ' + data.c1gender);
      if(data.c1age) body.appendParagraph('  • Age: ' + data.c1age);
      if(data.c1eth) body.appendParagraph('  • Ethnicity: ' + data.c1eth);
      if(data.c1accent) body.appendParagraph('  • Accent: ' + data.c1accent);
      if(data.c1clothing) body.appendParagraph('  • Clothing: ' + data.c1clothing);
      if(data.c1notes) body.appendParagraph('  • Notes: ' + data.c1notes);
    }
    if(data.c2gender) {
      body.appendParagraph('Character 2:');
      if(data.c2gender) body.appendParagraph('  • Gender: ' + data.c2gender);
      if(data.c2age) body.appendParagraph('  • Age: ' + data.c2age);
      if(data.c2eth) body.appendParagraph('  • Ethnicity: ' + data.c2eth);
      if(data.c2accent) body.appendParagraph('  • Accent: ' + data.c2accent);
      if(data.c2clothing) body.appendParagraph('  • Clothing: ' + data.c2clothing);
      if(data.c2notes) body.appendParagraph('  • Notes: ' + data.c2notes);
    }
    body.appendParagraph('').setSpacingAfter(12);

    // Scene & Music
    body.appendParagraph('Scene & Music').setHeading(DocumentApp.ParagraphHeading.HEADING2);
    if(data.background) body.appendParagraph('Background: ' + data.background);
    if(data.sceneDesc) body.appendParagraph('Scene Notes: ' + data.sceneDesc);
    if(data.titleScreen) body.appendParagraph('Title Screen: ' + data.titleScreen);
    if(data.music) body.appendParagraph('Music: ' + data.music);
    if(data.musicNotes) body.appendParagraph('Music Notes: ' + data.musicNotes);
    body.appendParagraph('').setSpacingAfter(12);

    // Script
    if(data.scriptTitle || data.scriptMethod) {
      body.appendParagraph('Script').setHeading(DocumentApp.ParagraphHeading.HEADING2);
      if(data.scriptTitle) body.appendParagraph('Title: ' + data.scriptTitle);
      if(data.scriptMethod) body.appendParagraph('Method: ' + data.scriptMethod);
      body.appendParagraph('').setSpacingAfter(12);
    }

    const docFile = DriveApp.getFileById(doc.getId());
    folder.addFile(docFile);
    DriveApp.getRootFolder().removeFile(docFile);
    Logger.log('Brief document created: ' + docTitle + ' in folder: ' + folder.getName());
    return doc.getUrl();
  } catch (e) {
    Logger.log('Error generating brief document: ' + e.toString());
    return null;
  }
}

function saveUploadedFiles(folder, data, clientLabel) {
  FILE_FIELDS.forEach(function (key) {
    var value = data[key];
    if (!value) return;
    // FILE_NAME_FIELDS carries the browser's original filename per upload
    // (e.g. "logoDataUrlName") - fall back to the field key if a client is
    // still on an older cached frontend that doesn't send it.
    var originalName = data[key + 'Name'] || key;
    saveBase64File(folder, value, originalName, clientLabel);
  });
}

function saveBase64File(folder, dataUrl, originalName, clientLabel) {
  var match = /^data:([^;]+);base64,(.*)$/.exec(dataUrl);
  if (!match) return null;
  var mimeType = match[1];
  var base64 = match[2];
  var bytes = Utilities.base64Decode(base64);
  var ext = (mimeType.split('/')[1] || 'bin').split('+')[0];
  var baseName = originalName.replace(/\.[a-zA-Z0-9]+$/, '') || originalName;
  var fileName = clientLabel ? (baseName + ' - ' + clientLabel + '.' + ext) : (baseName + '.' + ext);
  var blob = Utilities.newBlob(bytes, mimeType, fileName);
  return folder.createFile(blob);
}

// -- SHEET HELPERS ---------------------------------------------
function findColumnByHeader(sheet, headerName) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  for (let i = 0; i < headers.length; i++) {
    if (headers[i] === headerName) return i + 1;
  }
  return -1;
}

function findRowByColumnValue(sheet, col, value) {
  if (col === -1 || !value) return null;
  var numDataRows = sheet.getLastRow() - 1;
  // getRange() throws if asked for 0 rows - happens whenever the sheet is
  // down to just the header row (or completely empty), which is a valid
  // state (e.g. right after this script points at a brand new tab), not
  // an error - so it should just mean "no match found" instead of crashing
  // every lookup on this sheet from then on.
  if (numDataRows < 1) return null;
  const values = sheet.getRange(2, col, numDataRows, 1).getValues();
  for (let i = 0; i < values.length; i++) {
    if (values[i][0] === value) return i + 2; // 1-indexed, +1 for header row
  }
  return null;
}

function getColumnValue(sheet, row, headerName) {
  var col = findColumnByHeader(sheet, headerName);
  if (col === -1) return '';
  return sheet.getRange(row, col).getValue();
}

function setColumnValue(sheet, row, headerName, value) {
  var col = getOrCreateColumn(sheet, headerName);
  sheet.getRange(row, col).setValue(value);
}

function setColumnFormula(sheet, row, headerName, formula) {
  var col = getOrCreateColumn(sheet, headerName);
  sheet.getRange(row, col).setFormula(formula);
}

function getOrCreateColumn(sheet, headerName) {
  var col = findColumnByHeader(sheet, headerName);
  if (col !== -1) return col;
  var newCol = sheet.getLastColumn() + 1;
  sheet.getRange(1, newCol).setValue(headerName);
  return newCol;
}

function jsonOut(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

// -- ONE-TIME AUTHORIZATION HELPER ------------------------------
// Run this once manually from the editor (function dropdown -> select
// authorizeAllScopes -> Run) to grant every scope the project needs
// (Mail, UrlFetchApp for Slack, Drive, Sheets, Docs). See the "ONE-TIME
// AUTHORIZATION STEP" note in the file header for the full walkthrough.
// Safe to leave in permanently - it's never called automatically.
function authorizeAllScopes() {
  Logger.log('Requesting authorization for all scopes this project uses...');
  MailApp.getRemainingDailyQuota(); // touches Mail scope
  UrlFetchApp.fetch('https://www.google.com', { muteHttpExceptions: true }); // touches external request scope
  SpreadsheetApp.openById(SHEET_ID); // touches Sheets scope
  DriveApp.getRootFolder(); // touches Drive scope
  Logger.log('If you saw a permissions prompt and approved it, you are done - no redeploy needed.');
}
